% -------------------------------------------------------------------------
function all_experiments_multi_run = tempScriptMeasureClassificationPerformance(dataset, posneg_balance, classification_method, save_results, experiment_parent_dir)
% -------------------------------------------------------------------------
% Copyright (c) 2017, Amir-Hossein Karimi
% All rights reserved.

% Redistribution and use in source and binary forms, with or without
% modification, are permitted provided that the following conditions are
% met:
%     * Redistributions of source code must retain the above copyright
%       notice, this list of conditions and the following disclaimer.
%     * Redistributions in binary form must reproduce the above copyright
%       notice, this list of conditions and the following disclaimer in
%       the documentation and/or other materials provided with the distribution

% THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
% AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
% IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
% ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
% LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
% CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
% SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
% INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
% CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
% ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
% POSSIBILITY OF SUCH DAMAGE.

  % -------------------------------------------------------------------------
  %                                                                     Setup
  % -------------------------------------------------------------------------
  % classification_method = 'cnn';
  % classification_method = '1-knn';
  % classification_method = '3-knn';
  % classification_method = 'c-sep';
  % classification_method = 'libsvm';
  % classification_method = 'mlp-64-10';
  % classification_method = 'mlp-500-100';
  % classification_method = 'mlp-500-1000-100';
  number_of_trials = 10;
  all_experiments_multi_run = {};

  % -------------------------------------------------------------------------
  %                                                              opts.general
  % -------------------------------------------------------------------------
  opts.general.dataset = dataset;
  opts.general.posneg_balance = posneg_balance;
  opts.general.classification_method = classification_method;
  opts.general.number_of_trials = number_of_trials;

  % -------------------------------------------------------------------------
  %                                                                opts.paths
  % -------------------------------------------------------------------------
  opts.paths.time_string = sprintf('%s',datetime('now', 'Format', 'd-MMM-y-HH-mm-ss'));
  opts.paths.experiment_parent_dir = experiment_parent_dir;
  % opts.paths.experiment_parent_dir = getValueFromFieldOrDefault( ...
  %   {}, ... % no input_opts here! :)
  %   'experiment_parent_dir', ...
  %   fullfile(vl_rootnn, 'experiment_results'));
  opts.paths.experiment_dir = fullfile(opts.paths.experiment_parent_dir, sprintf( ...
    'test-classification-perf-%s-rp-tests-%s-%s-%s', ...
    opts.paths.time_string, ...
    classification_method, ...
    opts.general.dataset, ...
    opts.general.posneg_balance));
  if ~exist(opts.paths.experiment_dir)
    mkdir(opts.paths.experiment_dir);
  end
  opts.paths.options_file_path = fullfile(opts.paths.experiment_dir, '_options.txt');
  opts.paths.results_file_path = fullfile(opts.paths.experiment_dir, '_results.txt');

  % -------------------------------------------------------------------------
  %                          save experiment setup (don't save imdb or net!!)
  % -------------------------------------------------------------------------
  saveStruct2File(opts, opts.paths.options_file_path, 0);


  % -------------------------------------------------------------------------
  %                                                                      beef
  % -------------------------------------------------------------------------
  % [~, tmp_experiments] = setupExperimentsUsingProjectedImbds(dataset, posneg_balance, false, false);
  % for i = 1 : numel(tmp_experiments)
  projection_string_list = getProjectionList();
  for i = 1 : numel(projection_string_list)
    all_experiments_multi_run{i}.performance = [];
  end

  for kk = 1:number_of_trials
    afprintf(sprintf('[INFO] Testing trial #%d / %d ...\n', kk, number_of_trials));
    all_experiments_single_run = runAllExperimentsOnce(opts.paths.experiment_dir, dataset, posneg_balance, classification_method);
    for i = 1 : numel(all_experiments_single_run)
      all_experiments_multi_run{i}.performance(end+1) = all_experiments_single_run{i}.performance;
    end
    afprintf(sprintf('[INFO] done!\n'));

    % for i = 1 : numel(tmp_experiments)
    for i = 1 : numel(projection_string_list)
      all_experiments_multi_run{i}.performance_metric = classification_method;
      all_experiments_multi_run{i}.performance_mean = mean(all_experiments_multi_run{i}.performance);
      all_experiments_multi_run{i}.performance_std = std(all_experiments_multi_run{i}.performance);
    end

    % -------------------------------------------------------------------------
    %                                                               save output
    % -------------------------------------------------------------------------
    % don't amend file, but overwrite...
    if exist(opts.paths.results_file_path)
      delete(opts.paths.results_file_path);
    end
    saveStruct2File(all_experiments_multi_run, opts.paths.results_file_path, 0);
  end

  % plot_title = sprintf('classification perf - %s - %s - %s', classification_method, dataset, posneg_balance);
  % tempScriptPlotRPTests(all_experiments_multi_run, plot_title, save_results);






% -------------------------------------------------------------------------
function all_experiments_single_run = runAllExperimentsOnce(experiment_dir, dataset, posneg_balance, classification_method)
% -------------------------------------------------------------------------
  % afprintf(sprintf('[INFO] Setting up experiment imdbs...\n'));
  % [~, experiments] = setupExperimentsUsingProjectedImbds(dataset, posneg_balance, false, true);
  % afprintf(sprintf('done!\n'));

  fh_projection_utils = projectionUtils;

  projection_string_list = getProjectionList();

  [~, tmp_experiments] = setupExperimentsUsingProjectedImbds(dataset, posneg_balance, false, false);
  original_imdb = tmp_experiments{1}.imdb;

  % % zero-mean the imdb
  % tmp_imdb = getVectorizedImdb(original_imdb);
  % tmp_imdb.images.data = tmp_imdb.images.data - mean(tmp_imdb.images.data);
  % tmp_imdb = get4DImdb(tmp_imdb, size(original_imdb.images.data, 1), size(original_imdb.images.data, 2), size(original_imdb.images.data, 3), size(original_imdb.images.data, 4));
  % original_imdb = tmp_imdb;

  % % randomly shuffle sample pixels (should not affect dense RP, but should ruin ens. sparse RP)
  % % IMPORTANT... shuffle all samples the same way!
  % ix = randperm(size(original_imdb.images.data, 1) * size(original_imdb.images.data, 2) * size(original_imdb.images.data, 3));
  % for i = 1:size(original_imdb.images.data, 4)
  %   sample = original_imdb.images.data(:,:,:,i);
  %   vectorized_sample = reshape(sample, 1, []);
  %   shuffled_sample = reshape(vectorized_sample(ix), size(sample, 1), size(sample, 2), size(sample, 3));
  %   original_imdb.images.data(:,:,:,i) = shuffled_sample;
  % end


  % keyboard
  % original_imdb = tmp_experiments{1}.imdb.imdb;

  for i = 1 : numel(projection_string_list)
    projection_string = projection_string_list{i};
    afprintf(sprintf('[INFO] Testing experiment #%d / %d (projection_string: %s) ...', i, numel(projection_string_list), projection_string));


    experiment_options = {};
    if numel(strfind(projection_string, 'larpV0P0RL0')) > 0
      experiment_options.imdb = original_imdb;
    elseif numel(strfind(projection_string, 'pca')) > 0
      projected_dim = str2num(getStringParameterStartingAtIndex(projection_string, 18));
      experiment_options.imdb = fh_projection_utils.getPCAProjectedImdb(original_imdb, projected_dim);
    elseif numel(strfind(projection_string, 'custom')) > 0
      larp_weight_init_type = 'gaussian-IdentityCovariance-MuDivide-1-SigmaDivide-1';
      experiment_options.imdb = getProjectedImdbUsingMatConvNet(original_imdb, dataset, larp_weight_init_type, projection_string, -1);
    elseif numel(strfind(projection_string, 'densely-project-indep-row-into')) > 0
      experiment_options.imdb = getProjectedImdbSpecialFunction(original_imdb, projection_string, 'dense_gaussian_indep_row');
    elseif numel(strfind(projection_string, 'densely-project-rotated-row-into')) > 0
      experiment_options.imdb = getProjectedImdbSpecialFunction(original_imdb, projection_string, 'dense_gaussian_rotated_row');
    elseif numel(strfind(projection_string, 'sparsely-project-indep-row-into')) > 0
      experiment_options.imdb = getProjectedImdbSpecialFunction(original_imdb, projection_string, 'sparse_gaussian_indep_row');
    elseif numel(strfind(projection_string, 'sparsely-project-rotated-row-into')) > 0
      experiment_options.imdb = getProjectedImdbSpecialFunction(original_imdb, projection_string, 'sparse_gaussian_rotated_row');
    else
      throwException('[ERROR] projection_string unrecognized.');
    end

    experiment_options.dataset = dataset;
    experiment_options.posneg_balance = posneg_balance;
    experiment_options.experiment_parent_dir = experiment_dir;
    experiment_options.debug_flag = false;
    switch classification_method
      case '1-knn'
        experiment_options.number_of_nearest_neighbors = 1;
        performance = getSimpleTestAccuracyFromKnn(experiment_options);
      case '3-knn'
        experiment_options.number_of_nearest_neighbors = 3;
        performance = getSimpleTestAccuracyFromKnn(experiment_options);
      case 'c-sep'
        performance = getAverageClassCSeparation(experiment_options.imdb);
      case 'libsvm'
        performance = getSimpleTestAccuracyFromLibSvm(experiment_options);
      case 'mlp-64-10'
        experiment_options.number_of_hidden_nodes = [64, 10];
        performance = getSimpleTestAccuracyFromMLP(experiment_options);
      case 'mlp-500-100'
        experiment_options.number_of_hidden_nodes = [500, 100];
        performance = getSimpleTestAccuracyFromMLP(experiment_options);
      case 'mlp-500-1000-100'
        experiment_options.number_of_hidden_nodes = [500, 1000, 100];
        performance = getSimpleTestAccuracyFromMLP(experiment_options);
      case 'cnn'

        experiment_options.gpus = 3;

        % TODO: this has to somehow be detected automatically....
        % experiment_options.conv_network_arch = 'convV0P0RL0+fcV1-RF16CH64';
        % experiment_options.conv_network_arch = 'convV0P0RL0+fcV1-RF32CH64';

        % experiment_options.conv_network_arch = 'convV1P1RL1-RF32CH3+fcV1-RF16CH64';
        % experiment_options.conv_network_arch = 'convV3P1RL3-RF32CH3+fcV1-RF16CH64';
        % experiment_options.conv_network_arch = 'convV5P1RL5-RF32CH3+fcV1-RF16CH64';

        % experiment_options.conv_network_arch = 'convV1P0RL1-RF32CH3+fcV1-RF32CH64';
        % experiment_options.conv_network_arch = 'convV3P0RL3-RF32CH3+fcV1-RF32CH64';
        % experiment_options.conv_network_arch = 'convV5P0RL5-RF32CH3+fcV1-RF32CH64';

        % experiment_options.conv_network_arch = 'convV3P3RL3-RF32CH3+fcV1-RF4CH64-input64x64x3';
        experiment_options.conv_network_arch = 'convV3P3RL3-RF32CH3+fcV1-RF4CH64-input64x64x3-with-dropout';
        % experiment_options.conv_network_arch = 'convV5P3RL5-input64x64x3';

        [best_test_accuracy_mean, best_test_accuracy_std] = getSimpleTestAccuracyFromCnn(experiment_options);
        performance = best_test_accuracy_mean;
    end
    experiments{i}.performance = performance;
    afprintf(sprintf('[INFO] done!\n'));
  end

  all_experiments_single_run = experiments;



% -------------------------------------------------------------------------
function projected_imdb = getProjectedImdbSpecialFunction(original_imdb, projection_string, projection_layer_type)
% -------------------------------------------------------------------------
  fh_projection_utils = projectionUtils;
  index_offset = strfind(projection_string, '-into-') + 6;
  projected_dim = str2num(getStringParameterStartingAtIndex(projection_string, index_offset));
  number_in_ensemble = str2num(getStringParameterStartingAtIndex(projection_string, index_offset + length(num2str(projected_dim)) + 10));
  if strfind(projection_string, 'vector-max-pool')
    % projected_imdb = fh_projection_utils.getEnsembleDenselyDownProjectedImdb(original_imdb, 1, projection_layer_type, 1, 'pooling-max-vector-width-9-stride-1', projected_dim, number_in_ensemble);
    % projected_imdb = fh_projection_utils.getEnsembleDenselyDownProjectedImdb(original_imdb, 1, projection_layer_type, 1, 'pooling-max-vector-width-9-stride-4', projected_dim, number_in_ensemble);
    projected_imdb = fh_projection_utils.getEnsembleDenselyDownProjectedImdb(original_imdb, 1, projection_layer_type, 1, 'pooling-max-vector-width-4-stride-4', projected_dim, number_in_ensemble);
    % projected_imdb = fh_projection_utils.getEnsembleDenselyDownProjectedImdb(original_imdb, 1, projection_layer_type, 1, 'pooling-max-vector-width-16-stride-16', projected_dim, number_in_ensemble);
    % projected_imdb = fh_projection_utils.getEnsembleDenselyDownProjectedImdb(original_imdb, 1, projection_layer_type, 1, 'pooling-max-vector-width-25-stride-25', projected_dim, number_in_ensemble);
  elseif strfind(projection_string, 'vector-min-pool')
    projected_imdb = fh_projection_utils.getEnsembleDenselyDownProjectedImdb(original_imdb, 1, projection_layer_type, 1, 'pooling-min-vector-width-4-stride-4', projected_dim, number_in_ensemble);
    % projected_imdb = fh_projection_utils.getEnsembleDenselyDownProjectedImdb(original_imdb, 1, projection_layer_type, 1, 'pooling-min-vector-width-16-stride-16', projected_dim, number_in_ensemble);
  elseif strfind(projection_string, 'vector-avg-pool')
    projected_imdb = fh_projection_utils.getEnsembleDenselyDownProjectedImdb(original_imdb, 1, projection_layer_type, 1, 'pooling-avg-vector-width-4-stride-4', projected_dim, number_in_ensemble);
  elseif strfind(projection_string, 'vl-nn-max-pool')
    projected_imdb = fh_projection_utils.getEnsembleDenselyDownProjectedImdb(original_imdb, 1, projection_layer_type, 1, 'pooling-max-2x2-stride-2-pad-0000', projected_dim, number_in_ensemble);
    % projected_imdb = fh_projection_utils.getEnsembleDenselyDownProjectedImdb(original_imdb, 1, projection_layer_type, 1, 'pooling-max-3x3-stride-2-pad-0101', projected_dim, number_in_ensemble);
  else
    projected_imdb = fh_projection_utils.getEnsembleDenselyDownProjectedImdb(original_imdb, 1, projection_layer_type, 0, 'whatever', projected_dim, number_in_ensemble);
  end



% -------------------------------------------------------------------------
function projected_imdb = getProjectedImdbUsingMatConvNet(original_imdb, dataset, larp_weight_init_type, larp_network_arch, projection_depth)
% -------------------------------------------------------------------------
  fh_projection_utils = projectionUtils;
  larp_weight_init_sequence = getLarpWeightInitSequence(larp_weight_init_type, larp_network_arch);
  projection_net = fh_projection_utils.getProjectionNetworkObject(dataset, larp_network_arch, larp_weight_init_sequence);
  projected_imdb = fh_projection_utils.projectImdbThroughNetwork(original_imdb, projection_net, projection_depth);


% -------------------------------------------------------------------------
function projection_string_list = getProjectionList()
% -------------------------------------------------------------------------
  projection_string_list = { ...
    ... 'larpV3P3RL3-final-conv-16-kernels-first-max-pool-then-relu', ...
    ... 'larpV3P3RL3-final-conv-16-kernels-first-relu-then-max-pool', ...
    ...
    ...
    ...
    ... 'larpV0P0RL0', ...
    ...
    ...
    ... 'larpV0P0RL0', ...
    ... 'densely-project-indep-row-into-256-ensemble-1', ... % 256
    ... 'densely-project-indep-row-into-1024-ensemble-1-vector-max-pool', ... % 256
    ... 'densely-project-rotated-row-into-1024-ensemble-1-vector-max-pool', ... % 256
    ... 'densely-project-rotated-row-into-1024-ensemble-1-vl-nn-max-pool', ... % 256
    ... 'custom-1-L-63-99-1-max-pool', ... % 256
    ... 'custom-1-L-3-99-1-max-pool', ... % 256
    ...
    ...
    ...
    ...
    ...
    ...
    'larpV0P0RL0', ...
    ...
    'densely-project-indep-row-into-196-ensemble-1', ... % 196
    'densely-project-rotated-row-into-196-ensemble-1', ... % 196
    'sparsely-project-indep-row-into-196-ensemble-1', ... % 196
    'sparsely-project-rotated-row-into-196-ensemble-1', ... % 196
    ...
    'densely-project-indep-row-into-784-ensemble-1-vector-max-pool', ... % 196
    'densely-project-rotated-row-into-784-ensemble-1-vector-max-pool', ... % 196
    'sparsely-project-indep-row-into-784-ensemble-1-vector-max-pool', ... % 196
    'sparsely-project-rotated-row-into-784-ensemble-1-vector-max-pool', ... % 196
    ...
    'densely-project-indep-row-into-784-ensemble-1-vl-nn-max-pool', ... % 196
    'densely-project-rotated-row-into-784-ensemble-1-vl-nn-max-pool', ... % 196
    'sparsely-project-indep-row-into-784-ensemble-1-vl-nn-max-pool', ... % 196
    'sparsely-project-rotated-row-into-784-ensemble-1-vl-nn-max-pool', ... % 196
    ...
    'custom-1-L-63-99-1-max-pool', ... % 196
    'custom-1-L-3-99-1-max-pool', ... % 196
    ...
    ...
    ...
    ... ... 'sparsely-project-rotated-row-into-196-ensemble-1', ... % 196
    ... ... 'sparsely-project-rotated-row-into-784-ensemble-1-vl-nn-max-pool', ... % 196
    ... ... 'sparsely-project-rotated-row-into-784-ensemble-1-vector-max-pool', ... % 196
    ... ... 'custom-1-L-3-99-1', ... % 196
    ... ... 'custom-1-L-3-99-1-max-pool', ... % 196
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... 'pca-project-into-784', ...
    ... 'densely-project-indep-row-into-784-ensemble-1', ... % -max-pool
    ... 'densely-project-indep-row-into-784-ensemble-2', ... % -max-pool
    ... 'densely-project-indep-row-into-784-ensemble-4', ... % -max-pool
    ... 'densely-project-indep-row-into-784-ensemble-4-max-pool', ...
    ... 'densely-project-indep-row-into-784-ensemble-8-max-pool', ...
    ... 'densely-project-indep-row-into-784-ensemble-16-max-pool', ...
    ... 'custom-1-L-3-99-1', ... % -relu-max-pool
    ... 'custom-1-L-3-99-2', ... % -relu-max-pool
    ... 'custom-1-L-3-99-4', ... % -relu-max-pool
    ... 'custom-1-L-3-99-4-max-pool', ... % -relu
    ... 'custom-1-L-3-99-8-max-pool', ... % -relu
    ... 'custom-1-L-3-99-16-max-pool', ... % -relu
    ...
    ...
    ...
    ... 'pca-project-into-3072', ...
    ... 'densely-project-indep-row-into-3072-ensemble-1', ... % -max-pool
    ... 'densely-project-indep-row-into-3072-ensemble-2', ... % -max-pool
    ... 'densely-project-indep-row-into-3072-ensemble-4', ... % -max-pool
    ... 'densely-project-indep-row-into-3072-ensemble-4-max-pool', ...
    ... 'densely-project-indep-row-into-3072-ensemble-8-max-pool', ...
    ... 'densely-project-indep-row-into-3072-ensemble-16-max-pool', ...
    ... 'custom-1-L-3-99-3', ... % -relu-max-pool
    ... 'custom-1-L-3-99-6', ... % -relu-max-pool
    ... 'custom-1-L-3-99-12', ... % -relu-max-pool
    ... 'custom-1-L-3-99-12-max-pool', ... % -relu
    ... 'custom-1-L-3-99-24-max-pool', ... % -relu
    ... 'custom-1-L-3-99-48-max-pool', ... % -relu
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... % ANYTHING-under-100
    ... 'pca-project-into-1', ...
    ... 'pca-project-into-2', ...
    ... 'pca-project-into-4', ...
    ... 'pca-project-into-8', ...
    ... 'pca-project-into-16', ...
    ... 'pca-project-into-32', ...
    ...
    ... 'densely-project-indep-row-into-1-ensemble-1', ...
    ... 'densely-project-indep-row-into-2-ensemble-1', ...
    ... 'densely-project-indep-row-into-4-ensemble-1', ...
    ... 'densely-project-indep-row-into-8-ensemble-1', ...
    ... 'densely-project-indep-row-into-16-ensemble-1', ...
    ... 'densely-project-indep-row-into-32-ensemble-1', ...
    ...
    ... 'densely-project-indep-row-into-4-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-8-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-16-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-32-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-64-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-128-ensemble-1-vector-max-pool', ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... % MNIST-784
    ... 'pca-project-into-1', ...
    ... 'pca-project-into-2', ...
    ... 'pca-project-into-4', ...
    ... 'pca-project-into-8', ...
    ... 'pca-project-into-16', ...
    ... 'pca-project-into-32', ...
    ... 'pca-project-into-64', ...
    ... 'pca-project-into-128', ...
    ... 'pca-project-into-256', ...
    ... 'pca-project-into-512', ...
    ... 'pca-project-into-784', ...
    ...
    ... 'densely-project-indep-row-into-1-ensemble-1', ...
    ... 'densely-project-indep-row-into-2-ensemble-1', ...
    ... 'densely-project-indep-row-into-4-ensemble-1', ...
    ... 'densely-project-indep-row-into-8-ensemble-1', ...
    ... 'densely-project-indep-row-into-16-ensemble-1', ...
    ... 'densely-project-indep-row-into-32-ensemble-1', ...
    ... 'densely-project-indep-row-into-64-ensemble-1', ...
    ... 'densely-project-indep-row-into-128-ensemble-1', ...
    ... 'densely-project-indep-row-into-256-ensemble-1', ...
    ... 'densely-project-indep-row-into-512-ensemble-1', ...
    ... 'densely-project-indep-row-into-784-ensemble-1', ...
    ...
    ... 'densely-project-indep-row-into-4-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-8-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-16-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-32-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-64-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-128-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-256-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-512-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-1024-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-2048-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-3136-ensemble-1-vector-max-pool', ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... % ANYTHING-3072
    ... 'pca-project-into-1', ...
    ... 'pca-project-into-2', ...
    ... 'pca-project-into-4', ...
    ... 'pca-project-into-8', ...
    ... 'pca-project-into-16', ...
    ... 'pca-project-into-32', ...
    ... 'pca-project-into-64', ...
    ... 'pca-project-into-128', ...
    ... 'pca-project-into-256', ...
    ... 'pca-project-into-512', ...
    ... 'pca-project-into-1024', ...
    ... 'pca-project-into-2048', ...
    ... 'pca-project-into-3072', ...
    ... ... 'pca-project-into-4096', ...
    ...
    ... 'densely-project-indep-row-into-1-ensemble-1', ...
    ... 'densely-project-indep-row-into-2-ensemble-1', ...
    ... 'densely-project-indep-row-into-4-ensemble-1', ...
    ... 'densely-project-indep-row-into-8-ensemble-1', ...
    ... 'densely-project-indep-row-into-16-ensemble-1', ...
    ... 'densely-project-indep-row-into-32-ensemble-1', ...
    ... 'densely-project-indep-row-into-64-ensemble-1', ...
    ... 'densely-project-indep-row-into-128-ensemble-1', ...
    ... 'densely-project-indep-row-into-256-ensemble-1', ...
    ... 'densely-project-indep-row-into-512-ensemble-1', ...
    ... 'densely-project-indep-row-into-1024-ensemble-1', ...
    ... 'densely-project-indep-row-into-2048-ensemble-1', ...
    ... 'densely-project-indep-row-into-3072-ensemble-1', ...
    ... 'densely-project-indep-row-into-4096-ensemble-1', ...
    ...
    ... 'densely-project-indep-row-into-4-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-8-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-16-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-32-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-64-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-128-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-256-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-512-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-1024-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-2048-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-4096-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-8192-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-12288-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-16384-ensemble-1-vector-max-pool', ...
    ...
    ... 'densely-project-indep-row-into-4-ensemble-1-vector-min-pool', ...
    ... 'densely-project-indep-row-into-8-ensemble-1-vector-min-pool', ...
    ... 'densely-project-indep-row-into-16-ensemble-1-vector-min-pool', ...
    ... 'densely-project-indep-row-into-32-ensemble-1-vector-min-pool', ...
    ... 'densely-project-indep-row-into-64-ensemble-1-vector-min-pool', ...
    ... 'densely-project-indep-row-into-128-ensemble-1-vector-min-pool', ...
    ... 'densely-project-indep-row-into-256-ensemble-1-vector-min-pool', ...
    ... 'densely-project-indep-row-into-512-ensemble-1-vector-min-pool', ...
    ... 'densely-project-indep-row-into-1024-ensemble-1-vector-min-pool', ...
    ... 'densely-project-indep-row-into-2048-ensemble-1-vector-min-pool', ...
    ... 'densely-project-indep-row-into-4096-ensemble-1-vector-min-pool', ...
    ... 'densely-project-indep-row-into-8192-ensemble-1-vector-min-pool', ...
    ... 'densely-project-indep-row-into-12288-ensemble-1-vector-min-pool', ...
    ... 'densely-project-indep-row-into-16384-ensemble-1-vector-min-pool', ...
    ...
    ... 'densely-project-indep-row-into-4-ensemble-1-vector-avg-pool', ...
    ... 'densely-project-indep-row-into-8-ensemble-1-vector-avg-pool', ...
    ... 'densely-project-indep-row-into-16-ensemble-1-vector-avg-pool', ...
    ... 'densely-project-indep-row-into-32-ensemble-1-vector-avg-pool', ...
    ... 'densely-project-indep-row-into-64-ensemble-1-vector-avg-pool', ...
    ... 'densely-project-indep-row-into-128-ensemble-1-vector-avg-pool', ...
    ... 'densely-project-indep-row-into-256-ensemble-1-vector-avg-pool', ...
    ... 'densely-project-indep-row-into-512-ensemble-1-vector-avg-pool', ...
    ... 'densely-project-indep-row-into-1024-ensemble-1-vector-avg-pool', ...
    ... 'densely-project-indep-row-into-2048-ensemble-1-vector-avg-pool', ...
    ... 'densely-project-indep-row-into-4096-ensemble-1-vector-avg-pool', ...
    ... 'densely-project-indep-row-into-8192-ensemble-1-vector-avg-pool', ...
    ... 'densely-project-indep-row-into-12288-ensemble-1-vector-avg-pool', ...
    ... 'densely-project-indep-row-into-16384-ensemble-1-vector-avg-pool', ...
    ...
    ... 'densely-project-indep-row-into-16-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-32-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-64-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-128-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-256-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-512-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-1024-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-2048-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-4096-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-8192-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-16384-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-32768-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-49152-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-65536-ensemble-1-vector-max-pool', ...
    ...
    ... 'densely-project-indep-row-into-25-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-50-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-100-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-200-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-400-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-800-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-1600-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-3200-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-6400-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-12800-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-25600-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-51200-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-102400-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-204800-ensemble-1-vector-max-pool', ...
    ...
    ...
    ...
    ...
    ... ... ... ... % ANYTHING-3072 (add pooling to every layer, EXCEPT LAST)
    ... ... ... ... 'custom-1-L-3-99-1-max-pool', ... % 1024
    ... ... ... ... 'custom-1-L-3-99-2-max-pool', ... % 2048
    ... ... ... ... 'custom-1-L-3-99-4-max-pool', ... % 4096
    ... ... ... ...
    ... ... ... ... 'custom-2-L-3-16-1-max-pool', ... % 256
    ... ... ... ... 'custom-2-L-3-16-2-max-pool', ... % 512
    ... ... ... ... 'custom-2-L-3-16-4-max-pool', ... % 1024
    ... ... ... ... 'custom-2-L-3-16-8-max-pool', ... % 2048
    ... ... ... ... 'custom-2-L-3-16-16-max-pool', ... % 4096
    ... ... ... ...
    ... ... ... ... 'custom-3-L-3-16-1-max-pool', ... % 64
    ... ... ... ... 'custom-3-L-3-16-2-max-pool', ... % 128
    ... ... ... ... 'custom-3-L-3-16-4-max-pool', ... % 256
    ... ... ... ... 'custom-3-L-3-16-8-max-pool', ... % 512
    ... ... ... ... 'custom-3-L-3-16-16-max-pool', ... % 1024
    ... ... ... ... 'custom-3-L-3-16-32-max-pool', ... % 2048
    ... ... ... ... 'custom-3-L-3-16-64-max-pool', ... % 4096
    ... ... ... ...
    ... ... ... ... 'custom-4-L-3-16-1-max-pool', ... % 16
    ... ... ... ... 'custom-4-L-3-16-2-max-pool', ... % 32
    ... ... ... ... 'custom-4-L-3-16-4-max-pool', ... % 64
    ... ... ... ... 'custom-4-L-3-16-8-max-pool', ... % 128
    ... ... ... ... 'custom-4-L-3-16-16-max-pool', ... % 256
    ... ... ... ... 'custom-4-L-3-16-32-max-pool', ... % 512
    ... ... ... ... 'custom-4-L-3-16-64-max-pool', ... % 1024
    ... ... ... ... 'custom-4-L-3-16-128-max-pool', ... % 2048
    ... ... ... ... 'custom-4-L-3-16-256-max-pool', ... % 4096
    ... ... ... ...
    ... ... ... ... 'custom-5-L-3-16-1-max-pool', ... % 4
    ... ... ... ... 'custom-5-L-3-16-2-max-pool', ... % 8
    ... ... ... ... 'custom-5-L-3-16-4-max-pool', ... % 16
    ... ... ... ... 'custom-5-L-3-16-8-max-pool', ... % 32
    ... ... ... ... 'custom-5-L-3-16-16-max-pool', ... % 64
    ... ... ... ... 'custom-5-L-3-16-32-max-pool', ... % 128
    ... ... ... ... 'custom-5-L-3-16-64-max-pool', ... % 256
    ... ... ... ... 'custom-5-L-3-16-128-max-pool', ... % 512
    ... ... ... ... 'custom-5-L-3-16-256-max-pool', ... % 1024
    ... ... ... ... 'custom-5-L-3-16-512-max-pool', ... % 2048
    ... ... ... ... 'custom-5-L-3-16-1024-max-pool', ... % 4096
    ...
    ...
    ...
    ... % ANYTHING-3072 (add pooling to every layer)
    ... 'custom-1-L-3-99-1-max-pool', ... % 256
    ... 'custom-1-L-3-99-2-max-pool', ... % 512
    ... 'custom-1-L-3-99-4-max-pool', ... % 1024
    ... 'custom-1-L-3-99-8-max-pool', ... % 2048
    ... 'custom-1-L-3-99-16-max-pool', ... % 4096
    ...
    ... 'custom-2-L-3-16-1-max-pool', ... % 64
    ... 'custom-2-L-3-16-2-max-pool', ... % 128
    ... 'custom-2-L-3-16-4-max-pool', ... % 256
    ... 'custom-2-L-3-16-8-max-pool', ... % 512
    ... 'custom-2-L-3-16-16-max-pool', ... % 1024
    ... 'custom-2-L-3-16-32-max-pool', ... % 2048
    ... 'custom-2-L-3-16-64-max-pool', ... % 4096
    ...
    ... 'custom-2-L-3-64-1-max-pool', ... % 64
    ... 'custom-2-L-3-64-2-max-pool', ... % 128
    ... 'custom-2-L-3-64-4-max-pool', ... % 256
    ... 'custom-2-L-3-64-8-max-pool', ... % 512
    ... 'custom-2-L-3-64-16-max-pool', ... % 1024
    ... 'custom-2-L-3-64-32-max-pool', ... % 2048
    ... 'custom-2-L-3-64-64-max-pool', ... % 4096
    ...
    ... 'custom-3-L-3-16-1-max-pool', ... % 16
    ... 'custom-3-L-3-16-2-max-pool', ... % 32
    ... 'custom-3-L-3-16-4-max-pool', ... % 64
    ... 'custom-3-L-3-16-8-max-pool', ... % 128
    ... 'custom-3-L-3-16-16-max-pool', ... % 256
    ... 'custom-3-L-3-16-32-max-pool', ... % 512
    ... 'custom-3-L-3-16-64-max-pool', ... % 1024
    ... 'custom-3-L-3-16-128-max-pool', ... % 2048
    ... 'custom-3-L-3-16-256-max-pool', ... % 4096
    ...
    ... 'custom-3-L-3-256-1-max-pool', ... % 16
    ... 'custom-3-L-3-256-2-max-pool', ... % 32
    ... 'custom-3-L-3-256-4-max-pool', ... % 64
    ... 'custom-3-L-3-256-8-max-pool', ... % 128
    ... 'custom-3-L-3-256-16-max-pool', ... % 256
    ... 'custom-3-L-3-256-32-max-pool', ... % 512
    ... 'custom-3-L-3-256-64-max-pool', ... % 1024
    ... 'custom-3-L-3-256-128-max-pool', ... % 2048
    ... 'custom-3-L-3-256-256-max-pool', ... % 4096
    ...
    ... 'custom-4-L-3-16-1-max-pool', ... % 4
    ... 'custom-4-L-3-16-2-max-pool', ... % 8
    ... 'custom-4-L-3-16-4-max-pool', ... % 16
    ... 'custom-4-L-3-16-8-max-pool', ... % 32
    ... 'custom-4-L-3-16-16-max-pool', ... % 64
    ... 'custom-4-L-3-16-32-max-pool', ... % 128
    ... 'custom-4-L-3-16-64-max-pool', ... % 256
    ... 'custom-4-L-3-16-128-max-pool', ... % 512
    ... 'custom-4-L-3-16-256-max-pool', ... % 1024
    ... 'custom-4-L-3-16-512-max-pool', ... % 2048
    ... 'custom-4-L-3-16-1024-max-pool', ... % 4096
    ...
    ... 'custom-4-L-3-64-1-max-pool', ... % 4
    ... 'custom-4-L-3-64-2-max-pool', ... % 8
    ... 'custom-4-L-3-64-4-max-pool', ... % 16
    ... 'custom-4-L-3-64-8-max-pool', ... % 32
    ... 'custom-4-L-3-64-16-max-pool', ... % 64
    ... 'custom-4-L-3-64-32-max-pool', ... % 128
    ... 'custom-4-L-3-64-64-max-pool', ... % 256
    ... 'custom-4-L-3-64-128-max-pool', ... % 512
    ... 'custom-4-L-3-64-256-max-pool', ... % 1024
    ... 'custom-4-L-3-64-512-max-pool', ... % 2048
    ... 'custom-4-L-3-64-1024-max-pool', ... % 4096
    ...
    ... 'custom-4-L-3-256-1-max-pool', ... % 4
    ... 'custom-4-L-3-256-2-max-pool', ... % 8
    ... 'custom-4-L-3-256-4-max-pool', ... % 16
    ... 'custom-4-L-3-256-8-max-pool', ... % 32
    ... 'custom-4-L-3-256-16-max-pool', ... % 64
    ... 'custom-4-L-3-256-32-max-pool', ... % 128
    ... 'custom-4-L-3-256-64-max-pool', ... % 256
    ... 'custom-4-L-3-256-128-max-pool', ... % 512
    ... 'custom-4-L-3-256-256-max-pool', ... % 1024
    ... 'custom-4-L-3-256-512-max-pool', ... % 2048
    ... 'custom-4-L-3-256-1024-max-pool', ... % 4096
    ...
    ... 'custom-4-L-3-1024-1-max-pool', ... % 4
    ... 'custom-4-L-3-1024-2-max-pool', ... % 8
    ... 'custom-4-L-3-1024-4-max-pool', ... % 16
    ... 'custom-4-L-3-1024-8-max-pool', ... % 32
    ... 'custom-4-L-3-1024-16-max-pool', ... % 64
    ... 'custom-4-L-3-1024-32-max-pool', ... % 128
    ... 'custom-4-L-3-1024-64-max-pool', ... % 256
    ... 'custom-4-L-3-1024-128-max-pool', ... % 512
    ... 'custom-4-L-3-1024-256-max-pool', ... % 1024
    ... 'custom-4-L-3-1024-512-max-pool', ... % 2048
    ... 'custom-4-L-3-1024-1024-max-pool', ... % 4096
    ...
    ... 'custom-5-L-3-16-1-max-pool', ... % 1
    ... 'custom-5-L-3-16-2-max-pool', ... % 2
    ... 'custom-5-L-3-16-4-max-pool', ... % 4
    ... 'custom-5-L-3-16-8-max-pool', ... % 8
    ... 'custom-5-L-3-16-16-max-pool', ... % 16
    ... 'custom-5-L-3-16-32-max-pool', ... % 32
    ... 'custom-5-L-3-16-64-max-pool', ... % 64
    ... 'custom-5-L-3-16-128-max-pool', ... % 128
    ... 'custom-5-L-3-16-256-max-pool', ... % 256
    ... 'custom-5-L-3-16-512-max-pool', ... % 512
    ... 'custom-5-L-3-16-1024-max-pool', ... % 1024
    ... 'custom-5-L-3-16-2048-max-pool', ... % 2048
    ... 'custom-5-L-3-16-4096-max-pool', ... % 4096
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... % ANYTHING-5000+
    ... 'pca-project-into-1', ...
    ... 'pca-project-into-2', ...
    ... 'pca-project-into-4', ...
    ... 'pca-project-into-8', ...
    ... 'pca-project-into-16', ...
    ... 'pca-project-into-32', ...
    ... 'pca-project-into-64', ...
    ... 'pca-project-into-128', ...
    ... 'pca-project-into-256', ...
    ... 'pca-project-into-512', ...
    ... 'pca-project-into-1024', ...
    ... 'pca-project-into-2048', ...
    ... 'pca-project-into-4096', ...
    ... 'pca-project-into-5000', ...
    ...
    ... 'densely-project-indep-row-into-1-ensemble-1', ...
    ... 'densely-project-indep-row-into-2-ensemble-1', ...
    ... 'densely-project-indep-row-into-4-ensemble-1', ...
    ... 'densely-project-indep-row-into-8-ensemble-1', ...
    ... 'densely-project-indep-row-into-16-ensemble-1', ...
    ... 'densely-project-indep-row-into-32-ensemble-1', ...
    ... 'densely-project-indep-row-into-64-ensemble-1', ...
    ... 'densely-project-indep-row-into-128-ensemble-1', ...
    ... 'densely-project-indep-row-into-256-ensemble-1', ...
    ... 'densely-project-indep-row-into-512-ensemble-1', ...
    ... 'densely-project-indep-row-into-1024-ensemble-1', ...
    ... 'densely-project-indep-row-into-2048-ensemble-1', ...
    ... 'densely-project-indep-row-into-4096-ensemble-1', ...
    ... 'densely-project-indep-row-into-5000-ensemble-1', ...
    ...
    ... 'densely-project-indep-row-into-4-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-8-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-16-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-32-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-64-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-128-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-256-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-512-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-1024-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-2048-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-4096-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-8192-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-16384-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-20000-ensemble-1-vector-max-pool', ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... 'densely-project-indep-row-into-4-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-8-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-16-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-32-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-64-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-128-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-256-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-512-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-1024-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-2048-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-4096-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-8192-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-12288-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-16384-ensemble-1-vector-max-pool', ...
    ... ...
    ... ... 'densely-project-indep-row-into-1-ensemble-4-vector-max-pool', ...
    ... ... 'densely-project-indep-row-into-2-ensemble-4-vector-max-pool', ...
    ... 'densely-project-indep-row-into-4-ensemble-4-vector-max-pool', ...
    ... 'densely-project-indep-row-into-8-ensemble-4-vector-max-pool', ...
    ... 'densely-project-indep-row-into-16-ensemble-4-vector-max-pool', ...
    ... 'densely-project-indep-row-into-32-ensemble-4-vector-max-pool', ...
    ... 'densely-project-indep-row-into-64-ensemble-4-vector-max-pool', ...
    ... 'densely-project-indep-row-into-128-ensemble-4-vector-max-pool', ...
    ... 'densely-project-indep-row-into-256-ensemble-4-vector-max-pool', ...
    ... 'densely-project-indep-row-into-512-ensemble-4-vector-max-pool', ...
    ... 'densely-project-indep-row-into-1024-ensemble-4-vector-max-pool', ...
    ... 'densely-project-indep-row-into-2048-ensemble-4-vector-max-pool', ...
    ... 'densely-project-indep-row-into-3072-ensemble-4-vector-max-pool', ...
    ... 'densely-project-indep-row-into-4096-ensemble-4-vector-max-pool', ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... 'densely-project-indep-row-into-1-ensemble-1', ...
    ... 'densely-project-indep-row-into-2-ensemble-1', ...
    ... 'densely-project-indep-row-into-4-ensemble-1', ...
    ... 'densely-project-indep-row-into-8-ensemble-1', ...
    ... 'densely-project-indep-row-into-16-ensemble-1', ...
    ... 'densely-project-indep-row-into-32-ensemble-1', ...
    ... 'densely-project-indep-row-into-64-ensemble-1', ...
    ... 'densely-project-indep-row-into-128-ensemble-1', ...
    ... 'densely-project-indep-row-into-256-ensemble-1', ...
    ... 'densely-project-indep-row-into-512-ensemble-1', ...
    ... 'densely-project-indep-row-into-1024-ensemble-1', ...
    ... 'densely-project-indep-row-into-2048-ensemble-1', ...
    ... 'densely-project-indep-row-into-3072-ensemble-1', ...
    ... 'densely-project-indep-row-into-4096-ensemble-1', ...
    ...
    ... 'densely-project-indep-row-into-1-ensemble-2', ...
    ... 'densely-project-indep-row-into-2-ensemble-2', ...
    ... 'densely-project-indep-row-into-4-ensemble-2', ...
    ... 'densely-project-indep-row-into-8-ensemble-2', ...
    ... 'densely-project-indep-row-into-16-ensemble-2', ...
    ... 'densely-project-indep-row-into-32-ensemble-2', ...
    ... 'densely-project-indep-row-into-64-ensemble-2', ...
    ... 'densely-project-indep-row-into-128-ensemble-2', ...
    ... 'densely-project-indep-row-into-256-ensemble-2', ...
    ... 'densely-project-indep-row-into-512-ensemble-2', ...
    ... 'densely-project-indep-row-into-1024-ensemble-2', ...
    ... 'densely-project-indep-row-into-2048-ensemble-2', ...
    ...
    ... 'densely-project-indep-row-into-1-ensemble-4', ...
    ... 'densely-project-indep-row-into-2-ensemble-4', ...
    ... 'densely-project-indep-row-into-4-ensemble-4', ...
    ... 'densely-project-indep-row-into-8-ensemble-4', ...
    ... 'densely-project-indep-row-into-16-ensemble-4', ...
    ... 'densely-project-indep-row-into-32-ensemble-4', ...
    ... 'densely-project-indep-row-into-64-ensemble-4', ...
    ... 'densely-project-indep-row-into-128-ensemble-4', ...
    ... 'densely-project-indep-row-into-256-ensemble-4', ...
    ... 'densely-project-indep-row-into-512-ensemble-4', ...
    ... 'densely-project-indep-row-into-1024-ensemble-4', ...
    ...
    ... 'densely-project-indep-row-into-1-ensemble-8', ...
    ... 'densely-project-indep-row-into-2-ensemble-8', ...
    ... 'densely-project-indep-row-into-4-ensemble-8', ...
    ... 'densely-project-indep-row-into-8-ensemble-8', ...
    ... 'densely-project-indep-row-into-16-ensemble-8', ...
    ... 'densely-project-indep-row-into-32-ensemble-8', ...
    ... 'densely-project-indep-row-into-64-ensemble-8', ...
    ... 'densely-project-indep-row-into-128-ensemble-8', ...
    ... 'densely-project-indep-row-into-256-ensemble-8', ...
    ... 'densely-project-indep-row-into-512-ensemble-8', ...
    ...
    ... 'densely-project-indep-row-into-1-ensemble-16', ...
    ... 'densely-project-indep-row-into-2-ensemble-16', ...
    ... 'densely-project-indep-row-into-4-ensemble-16', ...
    ... 'densely-project-indep-row-into-8-ensemble-16', ...
    ... 'densely-project-indep-row-into-16-ensemble-16', ...
    ... 'densely-project-indep-row-into-32-ensemble-16', ...
    ... 'densely-project-indep-row-into-64-ensemble-16', ...
    ... 'densely-project-indep-row-into-128-ensemble-16', ...
    ... 'densely-project-indep-row-into-256-ensemble-16', ...
    ...
    ... 'densely-project-indep-row-into-1-ensemble-32', ...
    ... 'densely-project-indep-row-into-2-ensemble-32', ...
    ... 'densely-project-indep-row-into-4-ensemble-32', ...
    ... 'densely-project-indep-row-into-8-ensemble-32', ...
    ... 'densely-project-indep-row-into-16-ensemble-32', ...
    ... 'densely-project-indep-row-into-32-ensemble-32', ...
    ... 'densely-project-indep-row-into-64-ensemble-32', ...
    ... 'densely-project-indep-row-into-128-ensemble-32', ...
    ...
    ... 'densely-project-indep-row-into-1-ensemble-64', ...
    ... 'densely-project-indep-row-into-2-ensemble-64', ...
    ... 'densely-project-indep-row-into-4-ensemble-64', ...
    ... 'densely-project-indep-row-into-8-ensemble-64', ...
    ... 'densely-project-indep-row-into-16-ensemble-64', ...
    ... 'densely-project-indep-row-into-32-ensemble-64', ...
    ... 'densely-project-indep-row-into-64-ensemble-64', ...
    ...
    ... 'densely-project-indep-row-into-1-ensemble-128', ...
    ... 'densely-project-indep-row-into-2-ensemble-128', ...
    ... 'densely-project-indep-row-into-4-ensemble-128', ...
    ... 'densely-project-indep-row-into-8-ensemble-128', ...
    ... 'densely-project-indep-row-into-16-ensemble-128', ...
    ... 'densely-project-indep-row-into-32-ensemble-128', ...
    ...
    ... 'densely-project-indep-row-into-1-ensemble-256', ...
    ... 'densely-project-indep-row-into-2-ensemble-256', ...
    ... 'densely-project-indep-row-into-4-ensemble-256', ...
    ... 'densely-project-indep-row-into-8-ensemble-256', ...
    ... 'densely-project-indep-row-into-16-ensemble-256', ...
    ...
    ... 'densely-project-indep-row-into-1-ensemble-512', ...
    ... 'densely-project-indep-row-into-2-ensemble-512', ...
    ... 'densely-project-indep-row-into-4-ensemble-512', ...
    ... 'densely-project-indep-row-into-8-ensemble-512', ...
    ...
    ... 'densely-project-indep-row-into-1-ensemble-1024', ...
    ... 'densely-project-indep-row-into-2-ensemble-1024', ...
    ... 'densely-project-indep-row-into-4-ensemble-1024', ...
    ...
    ... 'densely-project-indep-row-into-1-ensemble-2048', ...
    ... 'densely-project-indep-row-into-2-ensemble-2048', ...
    ...
    ... 'densely-project-indep-row-into-1-ensemble-4096', ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... 'densely-project-indep-row-into-4-ensemble-1-max-pool', ...
    ... 'densely-project-indep-row-into-32-ensemble-1-max-pool', ...
    ... 'densely-project-indep-row-into-256-ensemble-1-max-pool', ...
    ... 'densely-project-indep-row-into-2048-ensemble-1-max-pool', ...
    ... 'densely-project-indep-row-into-16384-ensemble-1-max-pool', ...
    ...
    ... 'densely-project-indep-row-into-16-ensemble-2-max-pool', ...
    ... 'densely-project-indep-row-into-128-ensemble-2-max-pool', ...
    ... 'densely-project-indep-row-into-1024-ensemble-2-max-pool', ...
    ... 'densely-project-indep-row-into-8192-ensemble-2-max-pool', ...
    ...
    ... 'densely-project-indep-row-into-8-ensemble-4-max-pool', ...
    ... 'densely-project-indep-row-into-64-ensemble-4-max-pool', ...
    ... 'densely-project-indep-row-into-512-ensemble-4-max-pool', ...
    ... 'densely-project-indep-row-into-4096-ensemble-4-max-pool', ...
    ...
    ... 'densely-project-indep-row-into-4-ensemble-8-max-pool', ...
    ... 'densely-project-indep-row-into-32-ensemble-8-max-pool', ...
    ... 'densely-project-indep-row-into-256-ensemble-8-max-pool', ...
    ... 'densely-project-indep-row-into-2048-ensemble-8-max-pool', ...
    ...
    ... 'densely-project-indep-row-into-16-ensemble-16-max-pool', ...
    ... 'densely-project-indep-row-into-128-ensemble-16-max-pool', ...
    ... 'densely-project-indep-row-into-1024-ensemble-16-max-pool', ...
    ...
    ... 'densely-project-indep-row-into-8-ensemble-32-max-pool', ...
    ... 'densely-project-indep-row-into-64-ensemble-32-max-pool', ...
    ... 'densely-project-indep-row-into-512-ensemble-32-max-pool', ...
    ...
    ... 'densely-project-indep-row-into-4-ensemble-64-max-pool', ...
    ... 'densely-project-indep-row-into-32-ensemble-64-max-pool', ...
    ... 'densely-project-indep-row-into-256-ensemble-64-max-pool', ...
    ...
    ... 'densely-project-indep-row-into-16-ensemble-128-max-pool', ...
    ... 'densely-project-indep-row-into-128-ensemble-128-max-pool', ...
    ...
    ... 'densely-project-indep-row-into-8-ensemble-256-max-pool', ...
    ... 'densely-project-indep-row-into-64-ensemble-256-max-pool', ...
    ...
    ... 'densely-project-indep-row-into-4-ensemble-512-max-pool', ...
    ... 'densely-project-indep-row-into-32-ensemble-512-max-pool', ...
    ...
    ... 'densely-project-indep-row-into-16-ensemble-1024-max-pool', ...
    ...
    ... 'densely-project-indep-row-into-8-ensemble-2048-max-pool', ...
    ...
    ... 'densely-project-indep-row-into-4-ensemble-4096-max-pool', ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... ... 'densely-project-indep-row-into-1-ensemble-4-max-pool', ...
    ... 'densely-project-indep-row-into-8-ensemble-4-max-pool', ...
    ... 'densely-project-indep-row-into-64-ensemble-4-max-pool', ...
    ... 'densely-project-indep-row-into-512-ensemble-4-max-pool', ...
    ... 'densely-project-indep-row-into-4096-ensemble-4-max-pool', ...
    ...
    ... 'densely-project-indep-row-into-4-ensemble-8-max-pool', ...
    ... 'densely-project-indep-row-into-32-ensemble-8-max-pool', ...
    ... 'densely-project-indep-row-into-256-ensemble-8-max-pool', ...
    ... 'densely-project-indep-row-into-2048-ensemble-8-max-pool', ...
    ...
    ... ... 'densely-project-indep-row-into-2-ensemble-16-max-pool', ...
    ... 'densely-project-indep-row-into-16-ensemble-16-max-pool', ...
    ... 'densely-project-indep-row-into-128-ensemble-16-max-pool', ...
    ... 'densely-project-indep-row-into-1024-ensemble-16-max-pool', ...
    ...
    ... ... 'densely-project-indep-row-into-1-ensemble-32-max-pool', ...
    ... 'densely-project-indep-row-into-8-ensemble-32-max-pool', ...
    ... 'densely-project-indep-row-into-64-ensemble-32-max-pool', ...
    ... 'densely-project-indep-row-into-512-ensemble-32-max-pool', ...
    ...
    ... 'densely-project-indep-row-into-4-ensemble-64-max-pool', ...
    ... 'densely-project-indep-row-into-32-ensemble-64-max-pool', ...
    ... 'densely-project-indep-row-into-256-ensemble-64-max-pool', ...
    ...
    ... ... 'densely-project-indep-row-into-2-ensemble-128-max-pool', ...
    ... 'densely-project-indep-row-into-16-ensemble-128-max-pool', ...
    ... 'densely-project-indep-row-into-128-ensemble-128-max-pool', ...
    ...
    ... ... 'densely-project-indep-row-into-1-ensemble-256-max-pool', ...
    ... 'densely-project-indep-row-into-8-ensemble-256-max-pool', ...
    ... 'densely-project-indep-row-into-64-ensemble-256-max-pool', ...
    ...
    ... 'densely-project-indep-row-into-4-ensemble-512-max-pool', ...
    ... 'densely-project-indep-row-into-32-ensemble-512-max-pool', ...
    ...
    ... ... 'densely-project-indep-row-into-2-ensemble-1024-max-pool', ...
    ... 'densely-project-indep-row-into-16-ensemble-1024-max-pool', ...
    ...
    ... ... 'densely-project-indep-row-into-1-ensemble-2048-max-pool', ...
    ... 'densely-project-indep-row-into-8-ensemble-2048-max-pool', ...
    ...
    ... 'densely-project-indep-row-into-4-ensemble-4096-max-pool', ...
    ...
    ... ... 'densely-project-indep-row-into-2-ensemble-8192-max-pool', ...
    ...
    ... ... 'densely-project-indep-row-into-1-ensemble-16384-max-pool', ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... 'larpV0P0RL0', ...
    ...
    ...
    ... 'pca_project_into_1', ...
    ... 'pca_project_into_4', ...
    ... 'pca_project_into_9', ...
    ... 'pca_project_into_16', ...
    ...
    ...
    ... 'pca_project_into_1', ...
    ... 'pca_project_into_4', ...
    ... 'pca_project_into_16', ...
    ... 'pca_project_into_64', ...
    ... 'pca_project_into_256', ...
    ... 'pca_project_into_1024', ...
    ...
    ...
    ... 'pca_project_into_1', ...
    ... 'pca_project_into_49', ...
    ... 'pca_project_into_196', ...
    ... 'pca_project_into_784', ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... 'densely_project_into_1', ...
    ... 'densely_project_into_4', ...
    ... 'densely_project_into_16', ...
    ... 'densely_project_into_64', ...
    ... 'densely_project_into_256', ...
    ... 'densely_project_into_1024', ...
    ...
    ...
    ... 'densely_project_into_1', ...
    ... 'densely_project_into_49', ...
    ... 'densely_project_into_196', ...
    ... 'densely_project_into_784', ...
    ...
    ...
    ...
    ...
    ... 'custom-1-L-3-16-1-max-pool', ... % -relu
    ...
    ... 'custom-1-L-3-16-2-max-pool', ... % -relu
    ...
    ... 'custom-1-L-3-16-4-max-pool', ... % -relu
    ...
    ... 'custom-1-L-3-16-8-max-pool', ... % -relu
    ...
    ... 'custom-1-L-3-16-16-max-pool', ... % -relu
    ...
    ... 'custom-1-L-3-16-32-max-pool', ... % -relu
    ...
    ...
    ...
    ...
    ... 'custom-2-L-3-16-1-max-pool', ... % -relu
    ...
    ... 'custom-2-L-3-16-2-max-pool', ... % -relu
    ...
    ... 'custom-2-L-3-16-4-max-pool', ... % -relu
    ...
    ... 'custom-2-L-3-16-8-max-pool', ... % -relu
    ...
    ... 'custom-2-L-3-16-16-max-pool', ... % -relu
    ...
    ... 'custom-2-L-3-16-32-max-pool', ... % -relu
    ...
    ...
    ...
    ...
    ... 'custom-3-L-3-16-1-max-pool', ... % -relu
    ...
    ... 'custom-3-L-3-16-2-max-pool', ... % -relu
    ...
    ... 'custom-3-L-3-16-4-max-pool', ... % -relu
    ...
    ... 'custom-3-L-3-16-8-max-pool', ... % -relu
    ...
    ... 'custom-3-L-3-16-16-max-pool', ... % -relu
    ...
    ... 'custom-3-L-3-16-32-max-pool', ... % -relu
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... 'custom-5-L-3-4-4-max-pool', ... % relu-
    ... 'custom-5-L-3-4-16-max-pool', ... % relu-
    ... 'custom-5-L-3-4-64-max-pool', ... % relu-
    ... 'custom-5-L-3-4-256-max-pool', ... % relu-
    ... ...
    ... 'custom-5-L-5-4-4-max-pool', ... % relu-
    ... 'custom-5-L-5-4-16-max-pool', ... % relu-
    ... 'custom-5-L-5-4-64-max-pool', ... % relu-
    ... 'custom-5-L-5-4-256-max-pool', ... % relu-
    ... ...
    ... 'custom-5-L-7-4-4-max-pool', ... % relu-
    ... 'custom-5-L-7-4-16-max-pool', ... % relu-
    ... 'custom-5-L-7-4-64-max-pool', ... % relu-
    ... 'custom-5-L-7-4-256-max-pool', ... % relu-
    ... ... ...
    ... ... ...
    ... ... ...
    ... 'custom-5-L-3-16-4-max-pool', ... % relu-
    ... 'custom-5-L-3-16-16-max-pool', ... % relu-
    ... 'custom-5-L-3-16-64-max-pool', ... % relu-
    ... 'custom-5-L-3-16-256-max-pool', ... % relu-
    ... ...
    ... 'custom-5-L-5-16-4-max-pool', ... % relu-
    ... 'custom-5-L-5-16-16-max-pool', ... % relu-
    ... 'custom-5-L-5-16-64-max-pool', ... % relu-
    ... 'custom-5-L-5-16-256-max-pool', ... % relu-
    ... ...
    ... 'custom-5-L-7-16-4-max-pool', ... % relu-
    ... 'custom-5-L-7-16-16-max-pool', ... % relu-
    ... 'custom-5-L-7-16-64-max-pool', ... % relu-
    ... 'custom-5-L-7-16-256-max-pool', ... % relu-
    ... ... ...
    ... ... ...
    ... ... ...
    ... 'custom-5-L-3-64-4-max-pool', ... % relu-
    ... 'custom-5-L-3-64-16-max-pool', ... % relu-
    ... 'custom-5-L-3-64-64-max-pool', ... % relu-
    ... 'custom-5-L-3-64-256-max-pool', ... % relu-
    ... ...
    ... 'custom-5-L-5-64-4-max-pool', ... % relu-
    ... 'custom-5-L-5-64-16-max-pool', ... % relu-
    ... 'custom-5-L-5-64-64-max-pool', ... % relu-
    ... 'custom-5-L-5-64-256-max-pool', ... % relu-
    ... ...
    ... 'custom-5-L-7-64-4-max-pool', ... % relu-
    ... 'custom-5-L-7-64-16-max-pool', ... % relu-
    ... 'custom-5-L-7-64-64-max-pool', ... % relu-
    ... 'custom-5-L-7-64-256-max-pool', ... % relu-
    ... ... ...
    ... ... ...
    ... ... ...
    ... 'custom-5-L-3-256-4-max-pool', ... % relu-
    ... 'custom-5-L-3-256-16-max-pool', ... % relu-
    ... 'custom-5-L-3-256-64-max-pool', ... % relu-
    ... 'custom-5-L-3-256-256-max-pool', ... % relu-
    ... ...
    ... 'custom-5-L-5-256-4-max-pool', ... % relu-
    ... 'custom-5-L-5-256-16-max-pool', ... % relu-
    ... 'custom-5-L-5-256-64-max-pool', ... % relu-
    ... 'custom-5-L-5-256-256-max-pool', ... % relu-
    ... ...
    ... 'custom-5-L-7-256-4-max-pool', ... % relu-
    ... 'custom-5-L-7-256-16-max-pool', ... % relu-
    ... 'custom-5-L-7-256-64-max-pool', ... % relu-
    ... 'custom-5-L-7-256-256-max-pool', ... % relu-
    ... ...
    ... ...
    ... ...
    ... ...
    ... ...
    ... ...
    ... ...
    ... ...
    ... ...
    ... ...
    ... ...
    ... 'larpV0P0RL0', ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... 'custom-1-L-3-4-16-', ...                                                      % proj dim = 32 x 32 x 4 = 4096
    ... ... 'custom-1-L-3-4-16-relu', ...                                                  % proj dim = 32 x 32 x 4 = 4096
    ... 'custom-1-L-3-4-16-max-pool', ...                                              % proj dim = 32 x 32 x 4 / (4 ^ 1) = 1024
    ... 'custom-1-L-3-4-16-relu-max-pool', ...                                         % proj dim = 32 x 32 x 4 / (4 ^ 1) = 1024
    ... ... 'custom-1-L-7-4-16-', ...                                                      % proj dim = 32 x 32 x 4 = 4096
    ... ... 'custom-1-L-7-4-16-relu', ...                                                  % proj dim = 32 x 32 x 4 = 4096
    ... 'custom-1-L-7-4-16-max-pool', ...                                              % proj dim = 32 x 32 x 4 / (4 ^ 1) = 1024
    ... 'custom-1-L-7-4-16-relu-max-pool', ...                                         % proj dim = 32 x 32 x 4 / (4 ^ 1) = 1024
    ... ... 'custom-1-L-11-4-16-', ...                                                     % proj dim = 32 x 32 x 4 = 4096
    ... ... 'custom-1-L-11-4-16-relu', ...                                                 % proj dim = 32 x 32 x 4 = 4096
    ... 'custom-1-L-11-4-16-max-pool', ...                                             % proj dim = 32 x 32 x 4 / (4 ^ 1) = 1024
    ... 'custom-1-L-11-4-16-relu-max-pool', ...                                        % proj dim = 32 x 32 x 4 / (4 ^ 1) = 1024
    ... ... ...
    ... ... 'custom-1-L-3-16-16-', ...                                                     % proj dim = 32 x 32 x 16 = 16384
    ... ... 'custom-1-L-3-16-16-relu', ...                                                 % proj dim = 32 x 32 x 16 = 16384
    ... 'custom-1-L-3-16-16-max-pool', ...                                             % proj dim = 32 x 32 x 16 / (4 ^ 1) = 4096
    ... 'custom-1-L-3-16-16-relu-max-pool', ...                                        % proj dim = 32 x 32 x 16 / (4 ^ 1) = 4096
    ... ... 'custom-1-L-7-16-16-', ...                                                     % proj dim = 32 x 32 x 16 = 16384
    ... ... 'custom-1-L-7-16-16-relu', ...                                                 % proj dim = 32 x 32 x 16 = 16384
    ... 'custom-1-L-7-16-16-max-pool', ...                                             % proj dim = 32 x 32 x 16 / (4 ^ 1) = 4096
    ... 'custom-1-L-7-16-16-relu-max-pool', ...                                        % proj dim = 32 x 32 x 16 / (4 ^ 1) = 4096
    ... ... 'custom-1-L-11-16-16-', ...                                                    % proj dim = 32 x 32 x 16 = 16384
    ... ... 'custom-1-L-11-16-16-relu', ...                                                % proj dim = 32 x 32 x 16 = 16384
    ... 'custom-1-L-11-16-16-max-pool', ...                                            % proj dim = 32 x 32 x 16 / (4 ^ 1) = 4096
    ... 'custom-1-L-11-16-16-relu-max-pool', ...                                       % proj dim = 32 x 32 x 16 / (4 ^ 1) = 4096
    ... ... ...
    ... ... 'custom-1-L-3-64-16-', ...                                                     % proj dim = 32 x 32 x 64 = 65536
    ... ... 'custom-1-L-3-64-16-relu', ...                                                 % proj dim = 32 x 32 x 64 = 65536
    ... 'custom-1-L-3-64-16-max-pool', ...                                             % proj dim = 32 x 32 x 64 / (4 ^ 1) = 16384
    ... 'custom-1-L-3-64-16-relu-max-pool', ...                                        % proj dim = 32 x 32 x 64 / (4 ^ 1) = 16384
    ... ... 'custom-1-L-7-64-16-', ...                                                     % proj dim = 32 x 32 x 64 = 65536
    ... ... 'custom-1-L-7-64-16-relu', ...                                                 % proj dim = 32 x 32 x 64 = 65536
    ... 'custom-1-L-7-64-16-max-pool', ...                                             % proj dim = 32 x 32 x 64 / (4 ^ 1) = 16384
    ... 'custom-1-L-7-64-16-relu-max-pool', ...                                        % proj dim = 32 x 32 x 64 / (4 ^ 1) = 16384
    ... ... 'custom-1-L-11-64-16-', ...                                                    % proj dim = 32 x 32 x 64 = 65536
    ... ... 'custom-1-L-11-64-16-relu', ...                                                % proj dim = 32 x 32 x 64 = 65536
    ... 'custom-1-L-11-64-16-max-pool', ...                                            % proj dim = 32 x 32 x 64 / (4 ^ 1) = 16384
    ... 'custom-1-L-11-64-16-relu-max-pool', ...                                       % proj dim = 32 x 32 x 64 / (4 ^ 1) = 16384
    ... ... ...
    ... ... 'custom-1-L-3-256-16-', ...                                                    % proj dim = 32 x 32 x 256 = 262144
    ... ... 'custom-1-L-3-256-16-relu', ...                                                % proj dim = 32 x 32 x 256 = 262144
    ... 'custom-1-L-3-256-16-max-pool', ...                                            % proj dim = 32 x 32 x 256 / (4 ^ 1) = 65536
    ... 'custom-1-L-3-256-16-relu-max-pool', ...                                       % proj dim = 32 x 32 x 256 / (4 ^ 1) = 65536
    ... ... 'custom-1-L-7-256-16-', ...                                                    % proj dim = 32 x 32 x 256 = 262144
    ... ... 'custom-1-L-7-256-16-relu', ...                                                % proj dim = 32 x 32 x 256 = 262144
    ... 'custom-1-L-7-256-16-max-pool', ...                                            % proj dim = 32 x 32 x 256 / (4 ^ 1) = 65536
    ... 'custom-1-L-7-256-16-relu-max-pool', ...                                       % proj dim = 32 x 32 x 256 / (4 ^ 1) = 65536
    ... ... 'custom-1-L-11-256-16-', ...                                                   % proj dim = 32 x 32 x 256 = 262144
    ... ... 'custom-1-L-11-256-16-relu', ...                                               % proj dim = 32 x 32 x 256 = 262144
    ... 'custom-1-L-11-256-16-max-pool', ...                                           % proj dim = 32 x 32 x 256 / (4 ^ 1) = 65536
    ... 'custom-1-L-11-256-16-relu-max-pool', ...                                      % proj dim = 32 x 32 x 256 / (4 ^ 1) = 65536
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... 'custom-3-L-3-4-16-', ...                                                      % proj dim = 32 x 32 x 4 = 4096
    ... ... 'custom-3-L-3-4-16-relu', ...                                                  % proj dim = 32 x 32 x 4 = 4096
    ... 'custom-3-L-3-4-16-max-pool', ...                                              % proj dim = 32 x 32 x 4 / (4 ^ 3) = 64
    ... 'custom-3-L-3-4-16-relu-max-pool', ...                                         % proj dim = 32 x 32 x 4 / (4 ^ 3) = 64
    ... ... 'custom-3-L-7-4-16-', ...                                                      % proj dim = 32 x 32 x 4 = 4096
    ... ... 'custom-3-L-7-4-16-relu', ...                                                  % proj dim = 32 x 32 x 4 = 4096
    ... 'custom-3-L-7-4-16-max-pool', ...                                              % proj dim = 32 x 32 x 4 / (4 ^ 3) = 64
    ... 'custom-3-L-7-4-16-relu-max-pool', ...                                         % proj dim = 32 x 32 x 4 / (4 ^ 3) = 64
    ... ... 'custom-3-L-11-4-16-', ...                                                     % proj dim = 32 x 32 x 4 = 4096
    ... ... 'custom-3-L-11-4-16-relu', ...                                                 % proj dim = 32 x 32 x 4 = 4096
    ... 'custom-3-L-11-4-16-max-pool', ...                                             % proj dim = 32 x 32 x 4 / (4 ^ 3) = 64
    ... 'custom-3-L-11-4-16-relu-max-pool', ...                                        % proj dim = 32 x 32 x 4 / (4 ^ 3) = 64
    ... ... ...
    ... ... 'custom-3-L-3-16-16-', ...                                                     % proj dim = 32 x 32 x 16 = 16384
    ... ... 'custom-3-L-3-16-16-relu', ...                                                 % proj dim = 32 x 32 x 16 = 16384
    ... 'custom-3-L-3-16-16-max-pool', ...                                             % proj dim = 32 x 32 x 16 / (4 ^ 3) = 256
    ... 'custom-3-L-3-16-16-relu-max-pool', ...                                        % proj dim = 32 x 32 x 16 / (4 ^ 3) = 256
    ... ... 'custom-3-L-7-16-16-', ...                                                     % proj dim = 32 x 32 x 16 = 16384
    ... ... 'custom-3-L-7-16-16-relu', ...                                                 % proj dim = 32 x 32 x 16 = 16384
    ... 'custom-3-L-7-16-16-max-pool', ...                                             % proj dim = 32 x 32 x 16 / (4 ^ 3) = 256
    ... 'custom-3-L-7-16-16-relu-max-pool', ...                                        % proj dim = 32 x 32 x 16 / (4 ^ 3) = 256
    ... ... 'custom-3-L-11-16-16-', ...                                                    % proj dim = 32 x 32 x 16 = 16384
    ... ... 'custom-3-L-11-16-16-relu', ...                                                % proj dim = 32 x 32 x 16 = 16384
    ... 'custom-3-L-11-16-16-max-pool', ...                                            % proj dim = 32 x 32 x 16 / (4 ^ 3) = 256
    ... 'custom-3-L-11-16-16-relu-max-pool', ...                                       % proj dim = 32 x 32 x 16 / (4 ^ 3) = 256
    ... ... ...
    ... ... 'custom-3-L-3-64-16-', ...                                                     % proj dim = 32 x 32 x 64 = 65536
    ... ... 'custom-3-L-3-64-16-relu', ...                                                 % proj dim = 32 x 32 x 64 = 65536
    ... 'custom-3-L-3-64-16-max-pool', ...                                             % proj dim = 32 x 32 x 64 / (4 ^ 3) = 1024
    ... 'custom-3-L-3-64-16-relu-max-pool', ...                                        % proj dim = 32 x 32 x 64 / (4 ^ 3) = 1024
    ... ... 'custom-3-L-7-64-16-', ...                                                     % proj dim = 32 x 32 x 64 = 65536
    ... ... 'custom-3-L-7-64-16-relu', ...                                                 % proj dim = 32 x 32 x 64 = 65536
    ... 'custom-3-L-7-64-16-max-pool', ...                                             % proj dim = 32 x 32 x 64 / (4 ^ 3) = 1024
    ... 'custom-3-L-7-64-16-relu-max-pool', ...                                        % proj dim = 32 x 32 x 64 / (4 ^ 3) = 1024
    ... ... 'custom-3-L-11-64-16-', ...                                                    % proj dim = 32 x 32 x 64 = 65536
    ... ... 'custom-3-L-11-64-16-relu', ...                                                % proj dim = 32 x 32 x 64 = 65536
    ... 'custom-3-L-11-64-16-max-pool', ...                                            % proj dim = 32 x 32 x 64 / (4 ^ 3) = 1024
    ... 'custom-3-L-11-64-16-relu-max-pool', ...                                       % proj dim = 32 x 32 x 64 / (4 ^ 3) = 1024
    ... ... ...
    ... ... 'custom-3-L-3-256-16-', ...                                                    % proj dim = 32 x 32 x 256 = 262144
    ... ... 'custom-3-L-3-256-16-relu', ...                                                % proj dim = 32 x 32 x 256 = 262144
    ... 'custom-3-L-3-256-16-max-pool', ...                                            % proj dim = 32 x 32 x 256 / (4 ^ 3) = 4096
    ... 'custom-3-L-3-256-16-relu-max-pool', ...                                       % proj dim = 32 x 32 x 256 / (4 ^ 3) = 4096
    ... ... 'custom-3-L-7-256-16-', ...                                                    % proj dim = 32 x 32 x 256 = 262144
    ... ... 'custom-3-L-7-256-16-relu', ...                                                % proj dim = 32 x 32 x 256 = 262144
    ... 'custom-3-L-7-256-16-max-pool', ...                                            % proj dim = 32 x 32 x 256 / (4 ^ 3) = 4096
    ... 'custom-3-L-7-256-16-relu-max-pool', ...                                       % proj dim = 32 x 32 x 256 / (4 ^ 3) = 4096
    ... ... 'custom-3-L-11-256-16-', ...                                                   % proj dim = 32 x 32 x 256 = 262144
    ... ... 'custom-3-L-11-256-16-relu', ...                                               % proj dim = 32 x 32 x 256 = 262144
    ... 'custom-3-L-11-256-16-max-pool', ...                                           % proj dim = 32 x 32 x 256 / (4 ^ 3) = 4096
    ... 'custom-3-L-11-256-16-relu-max-pool', ...                                      % proj dim = 32 x 32 x 256 / (4 ^ 3) = 4096
    ... ... ...
    ... ... 'custom-3-L-3-1024-16-', ...                                                   % proj dim = 32 x 32 x 1024 = 1048576
    ... ... 'custom-3-L-3-1024-16-relu', ...                                               % proj dim = 32 x 32 x 1024 = 1048576
    ... 'custom-3-L-3-1024-16-max-pool', ...                                           % proj dim = 32 x 32 x 1024 / (4 ^ 3) = 16384
    ... 'custom-3-L-3-1024-16-relu-max-pool', ...                                      % proj dim = 32 x 32 x 1024 / (4 ^ 3) = 16384
    ... ... 'custom-3-L-7-1024-16-', ...                                                   % proj dim = 32 x 32 x 1024 = 1048576
    ... ... 'custom-3-L-7-1024-16-relu', ...                                               % proj dim = 32 x 32 x 1024 = 1048576
    ... 'custom-3-L-7-1024-16-max-pool', ...                                           % proj dim = 32 x 32 x 1024 / (4 ^ 3) = 16384
    ... 'custom-3-L-7-1024-16-relu-max-pool', ...                                      % proj dim = 32 x 32 x 1024 / (4 ^ 3) = 16384
    ... ... 'custom-3-L-11-1024-16-', ...                                                  % proj dim = 32 x 32 x 1024 = 1048576
    ... ... 'custom-3-L-11-1024-16-relu', ...                                              % proj dim = 32 x 32 x 1024 = 1048576
    ... 'custom-3-L-11-1024-16-max-pool', ...                                          % proj dim = 32 x 32 x 1024 / (4 ^ 3) = 16384
    ... 'custom-3-L-11-1024-16-relu-max-pool', ...                                     % proj dim = 32 x 32 x 1024 / (4 ^ 3) = 16384
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... ...
    ... ... 'custom-5-L-3-4-16-', ...                                                      % proj dim = 32 x 32 x 4 = 4096
    ... ... 'custom-5-L-3-4-16-relu', ...                                                  % proj dim = 32 x 32 x 4 = 4096
    ... 'custom-5-L-3-4-16-max-pool', ...                                              % proj dim = 32 x 32 x 4 / (4 ^ 5) = 4
    ... 'custom-5-L-3-4-16-relu-max-pool', ...                                         % proj dim = 32 x 32 x 4 / (4 ^ 5) = 4
    ... ... 'custom-5-L-7-4-16-', ...                                                      % proj dim = 32 x 32 x 4 = 4096
    ... ... 'custom-5-L-7-4-16-relu', ...                                                  % proj dim = 32 x 32 x 4 = 4096
    ... 'custom-5-L-7-4-16-max-pool', ...                                              % proj dim = 32 x 32 x 4 / (4 ^ 5) = 4
    ... 'custom-5-L-7-4-16-relu-max-pool', ...                                         % proj dim = 32 x 32 x 4 / (4 ^ 5) = 4
    ... ... 'custom-5-L-11-4-16-', ...                                                     % proj dim = 32 x 32 x 4 = 4096
    ... ... 'custom-5-L-11-4-16-relu', ...                                                 % proj dim = 32 x 32 x 4 = 4096
    ... 'custom-5-L-11-4-16-max-pool', ...                                             % proj dim = 32 x 32 x 4 / (4 ^ 5) = 4
    ... 'custom-5-L-11-4-16-relu-max-pool', ...                                        % proj dim = 32 x 32 x 4 / (4 ^ 5) = 4
    ... ... ...
    ... ... 'custom-5-L-3-16-16-', ...                                                     % proj dim = 32 x 32 x 16 = 16384
    ... ... 'custom-5-L-3-16-16-relu', ...                                                 % proj dim = 32 x 32 x 16 = 16384
    ... 'custom-5-L-3-16-16-max-pool', ...                                             % proj dim = 32 x 32 x 16 / (4 ^ 5) = 16
    ... 'custom-5-L-3-16-16-relu-max-pool', ...                                        % proj dim = 32 x 32 x 16 / (4 ^ 5) = 16
    ... ... 'custom-5-L-7-16-16-', ...                                                     % proj dim = 32 x 32 x 16 = 16384
    ... ... 'custom-5-L-7-16-16-relu', ...                                                 % proj dim = 32 x 32 x 16 = 16384
    ... 'custom-5-L-7-16-16-max-pool', ...                                             % proj dim = 32 x 32 x 16 / (4 ^ 5) = 16
    ... 'custom-5-L-7-16-16-relu-max-pool', ...                                        % proj dim = 32 x 32 x 16 / (4 ^ 5) = 16
    ... ... 'custom-5-L-11-16-16-', ...                                                    % proj dim = 32 x 32 x 16 = 16384
    ... ... 'custom-5-L-11-16-16-relu', ...                                                % proj dim = 32 x 32 x 16 = 16384
    ... 'custom-5-L-11-16-16-max-pool', ...                                            % proj dim = 32 x 32 x 16 / (4 ^ 5) = 16
    ... 'custom-5-L-11-16-16-relu-max-pool', ...                                       % proj dim = 32 x 32 x 16 / (4 ^ 5) = 16
    ... ... ...
    ... ... 'custom-5-L-3-64-16-', ...                                                     % proj dim = 32 x 32 x 64 = 65536
    ... ... 'custom-5-L-3-64-16-relu', ...                                                 % proj dim = 32 x 32 x 64 = 65536
    ... 'custom-5-L-3-64-16-max-pool', ...                                             % proj dim = 32 x 32 x 64 / (4 ^ 5) = 64
    ... 'custom-5-L-3-64-16-relu-max-pool', ...                                        % proj dim = 32 x 32 x 64 / (4 ^ 5) = 64
    ... ... 'custom-5-L-7-64-16-', ...                                                     % proj dim = 32 x 32 x 64 = 65536
    ... ... 'custom-5-L-7-64-16-relu', ...                                                 % proj dim = 32 x 32 x 64 = 65536
    ... 'custom-5-L-7-64-16-max-pool', ...                                             % proj dim = 32 x 32 x 64 / (4 ^ 5) = 64
    ... 'custom-5-L-7-64-16-relu-max-pool', ...                                        % proj dim = 32 x 32 x 64 / (4 ^ 5) = 64
    ... ... 'custom-5-L-11-64-16-', ...                                                    % proj dim = 32 x 32 x 64 = 65536
    ... ... 'custom-5-L-11-64-16-relu', ...                                                % proj dim = 32 x 32 x 64 = 65536
    ... 'custom-5-L-11-64-16-max-pool', ...                                            % proj dim = 32 x 32 x 64 / (4 ^ 5) = 64
    ... 'custom-5-L-11-64-16-relu-max-pool', ...                                       % proj dim = 32 x 32 x 64 / (4 ^ 5) = 64
    ... ... ...
    ... ... 'custom-5-L-3-256-16-', ...                                                    % proj dim = 32 x 32 x 256 = 262144
    ... ... 'custom-5-L-3-256-16-relu', ...                                                % proj dim = 32 x 32 x 256 = 262144
    ... 'custom-5-L-3-256-16-max-pool', ...                                            % proj dim = 32 x 32 x 256 / (4 ^ 5) = 256
    ... 'custom-5-L-3-256-16-relu-max-pool', ...                                       % proj dim = 32 x 32 x 256 / (4 ^ 5) = 256
    ... ... 'custom-5-L-7-256-16-', ...                                                    % proj dim = 32 x 32 x 256 = 262144
    ... ... 'custom-5-L-7-256-16-relu', ...                                                % proj dim = 32 x 32 x 256 = 262144
    ... 'custom-5-L-7-256-16-max-pool', ...                                            % proj dim = 32 x 32 x 256 / (4 ^ 5) = 256
    ... 'custom-5-L-7-256-16-relu-max-pool', ...                                       % proj dim = 32 x 32 x 256 / (4 ^ 5) = 256
    ... ... 'custom-5-L-11-256-16-', ...                                                   % proj dim = 32 x 32 x 256 = 262144
    ... ... 'custom-5-L-11-256-16-relu', ...                                               % proj dim = 32 x 32 x 256 = 262144
    ... 'custom-5-L-11-256-16-max-pool', ...                                           % proj dim = 32 x 32 x 256 / (4 ^ 5) = 256
    ... 'custom-5-L-11-256-16-relu-max-pool', ...                                      % proj dim = 32 x 32 x 256 / (4 ^ 5) = 256
    ... ... ...
    ... ... 'custom-5-L-3-1024-16-', ...                                                   % proj dim = 32 x 32 x 1024 = 1048576
    ... ... 'custom-5-L-3-1024-16-relu', ...                                               % proj dim = 32 x 32 x 1024 = 1048576
    ... 'custom-5-L-3-1024-16-max-pool', ...                                           % proj dim = 32 x 32 x 1024 / (4 ^ 5) = 1024
    ... 'custom-5-L-3-1024-16-relu-max-pool', ...                                       % proj dim = 32 x 32 x 1024 / (4 ^ 5) = 1024
    ... ... 'custom-5-L-7-1024-16-', ...                                                   % proj dim = 32 x 32 x 1024 = 1048576
    ... ... 'custom-5-L-7-1024-16-relu', ...                                               % proj dim = 32 x 32 x 1024 = 1048576
    ... 'custom-5-L-7-1024-16-max-pool', ...                                           % proj dim = 32 x 32 x 1024 / (4 ^ 5) = 1024
    ... 'custom-5-L-7-1024-16-relu-max-pool', ...                                       % proj dim = 32 x 32 x 1024 / (4 ^ 5) = 1024
    ... ... 'custom-5-L-11-1024-16-', ...                                                  % proj dim = 32 x 32 x 1024 = 1048576
    ... ... 'custom-5-L-11-1024-16-relu', ...                                              % proj dim = 32 x 32 x 1024 = 1048576
    ... 'custom-5-L-11-1024-16-max-pool', ...                                          % proj dim = 32 x 32 x 1024 / (4 ^ 5) = 1024
    ... 'custom-5-L-11-1024-16-relu-max-pool', ...                                      % proj dim = 32 x 32 x 1024 / (4 ^ 5) = 1024
    ... ...
    ... ... ... 'custom-5-L-3-4096-16-', ...                                                   % proj dim = 32 x 32 x 4096 = 4194304
    ... ... ... 'custom-5-L-3-4096-16-relu', ...                                               % proj dim = 32 x 32 x 4096 = 4194304
    ... ... 'custom-5-L-3-4096-16-max-pool', ...                                            % proj dim = 32 x 32 x 4096 / (4 ^ 5) = 4096
    ... ... 'custom-5-L-3-4096-16-relu-max-pool', ...                                       % proj dim = 32 x 32 x 4096 / (4 ^ 5) = 4096
    ... ... ... 'custom-5-L-7-4096-16-', ...                                                   % proj dim = 32 x 32 x 4096 = 4194304
    ... ... ... 'custom-5-L-7-4096-16-relu', ...                                               % proj dim = 32 x 32 x 4096 = 4194304
    ... ... 'custom-5-L-7-4096-16-max-pool', ...                                            % proj dim = 32 x 32 x 4096 / (4 ^ 5) = 4096
    ... ... 'custom-5-L-7-4096-16-relu-max-pool', ...                                       % proj dim = 32 x 32 x 4096 / (4 ^ 5) = 4096
    ... ... ... 'custom-5-L-11-4096-16-', ...                                                  % proj dim = 32 x 32 x 4096 = 4194304
    ... ... ... 'custom-5-L-11-4096-16-relu', ...                                              % proj dim = 32 x 32 x 4096 = 4194304
    ... ... 'custom-5-L-11-4096-16-max-pool', ...                                           % proj dim = 32 x 32 x 4096 / (4 ^ 5) = 4096
    ... ... 'custom-5-L-11-4096-16-relu-max-pool', ...                                      % proj dim = 32 x 32 x 4096 / (4 ^ 5) = 4096
  };




















