% -------------------------------------------------------------------------
function all_experiments_multi_run = tempScriptMeasureClassificationPerformance(dataset, posneg_balance, classification_method, save_results, experiment_parent_dir)
% -------------------------------------------------------------------------
% Copyright (c) 2017, Amir-Hossein Karimi
% All rights reserved.

% Redistribution and use in source and binary forms, with or without
% modification, are permitted provided that the following conditions are
% met:
%     * Redistributions of source code must retain the above copyright
%       notice, this list of conditions and the following disclaimer.
%     * Redistributions in binary form must reproduce the above copyright
%       notice, this list of conditions and the following disclaimer in
%       the documentation and/or other materials provided with the distribution

% THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
% AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
% IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
% ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
% LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
% CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
% SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
% INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
% CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
% ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
% POSSIBILITY OF SUCH DAMAGE.

  % -------------------------------------------------------------------------
  %                                                                     Setup
  % -------------------------------------------------------------------------
  % classification_method = 'cnn';
  % classification_method = '1-knn';
  % classification_method = '3-knn';
  % classification_method = 'c-sep';
  % classification_method = 'libsvm';
  % classification_method = 'mlp-64-10';
  % classification_method = 'mlp-500-100';
  % classification_method = 'mlp-500-1000-100';
  number_of_trials = 10;
  all_experiments_multi_run = {};

  % -------------------------------------------------------------------------
  %                                                              opts.general
  % -------------------------------------------------------------------------
  opts.general.dataset = dataset;
  opts.general.posneg_balance = posneg_balance;
  opts.general.classification_method = classification_method;
  opts.general.number_of_trials = number_of_trials;

  % -------------------------------------------------------------------------
  %                                                                opts.paths
  % -------------------------------------------------------------------------
  opts.paths.time_string = sprintf('%s',datetime('now', 'Format', 'd-MMM-y-HH-mm-ss'));
  opts.paths.experiment_parent_dir = experiment_parent_dir;
  % opts.paths.experiment_parent_dir = getValueFromFieldOrDefault( ...
  %   {}, ... % no input_opts here! :)
  %   'experiment_parent_dir', ...
  %   fullfile(vl_rootnn, 'experiment_results'));
  opts.paths.experiment_dir = fullfile(opts.paths.experiment_parent_dir, sprintf( ...
    'test-classification-perf-%s-rp-tests-%s-%s-%s', ...
    opts.paths.time_string, ...
    classification_method, ...
    opts.general.dataset, ...
    opts.general.posneg_balance));
  if ~exist(opts.paths.experiment_dir)
    mkdir(opts.paths.experiment_dir);
  end
  opts.paths.options_file_path = fullfile(opts.paths.experiment_dir, '_options.txt');
  opts.paths.results_file_path = fullfile(opts.paths.experiment_dir, '_results.txt');

  % -------------------------------------------------------------------------
  %                          save experiment setup (don't save imdb or net!!)
  % -------------------------------------------------------------------------
  saveStruct2File(opts, opts.paths.options_file_path, 0);


  % -------------------------------------------------------------------------
  %                                                                      beef
  % -------------------------------------------------------------------------
  % [~, tmp_experiments] = setupExperimentsUsingProjectedImbds(dataset, posneg_balance, false, false);
  % for i = 1 : numel(tmp_experiments)
  projection_string_list = getProjectionList();
  for i = 1 : numel(projection_string_list)
    all_experiments_multi_run{i}.performance = [];
  end

  for kk = 1:number_of_trials
    afprintf(sprintf('[INFO] Testing trial #%d / %d ...\n', kk, number_of_trials));
    all_experiments_single_run = runAllExperimentsOnce(opts.paths.experiment_dir, dataset, posneg_balance, classification_method);
    for i = 1 : numel(all_experiments_single_run)
      all_experiments_multi_run{i}.performance(end+1) = all_experiments_single_run{i}.performance;
    end
    afprintf(sprintf('[INFO] done!\n'));

    % for i = 1 : numel(tmp_experiments)
    for i = 1 : numel(projection_string_list)
      all_experiments_multi_run{i}.performance_metric = classification_method;
      all_experiments_multi_run{i}.performance_mean = mean(all_experiments_multi_run{i}.performance);
      all_experiments_multi_run{i}.performance_std = std(all_experiments_multi_run{i}.performance);
    end

    % -------------------------------------------------------------------------
    %                                                               save output
    % -------------------------------------------------------------------------
    % don't amend file, but overwrite...
    if exist(opts.paths.results_file_path)
      delete(opts.paths.results_file_path);
    end
    saveStruct2File(all_experiments_multi_run, opts.paths.results_file_path, 0);
  end

  % plot_title = sprintf('classification perf - %s - %s - %s', classification_method, dataset, posneg_balance);
  % tempScriptPlotRPTests(all_experiments_multi_run, plot_title, save_results);






% -------------------------------------------------------------------------
function all_experiments_single_run = runAllExperimentsOnce(experiment_dir, dataset, posneg_balance, classification_method)
% -------------------------------------------------------------------------
  % afprintf(sprintf('[INFO] Setting up experiment imdbs...\n'));
  % [~, experiments] = setupExperimentsUsingProjectedImbds(dataset, posneg_balance, false, true);
  % afprintf(sprintf('done!\n'));

  fh_projection_utils = projectionUtils;

  projection_string_list = getProjectionList();

  [~, tmp_experiments] = setupExperimentsUsingProjectedImbds(dataset, posneg_balance, false, false);
  original_imdb = tmp_experiments{1}.imdb;

  % % zero-mean the imdb
  % tmp_imdb = getVectorizedImdb(original_imdb);
  % tmp_imdb.images.data = tmp_imdb.images.data - mean(tmp_imdb.images.data);
  % tmp_imdb = get4DImdb(tmp_imdb, size(original_imdb.images.data, 1), size(original_imdb.images.data, 2), size(original_imdb.images.data, 3), size(original_imdb.images.data, 4));
  % original_imdb = tmp_imdb;

  % % randomly shuffle sample pixels (should not affect dense RP, but should ruin ens. sparse RP)
  % % IMPORTANT... shuffle all samples the same way!
  % ix = randperm(size(original_imdb.images.data, 1) * size(original_imdb.images.data, 2) * size(original_imdb.images.data, 3));
  % for i = 1:size(original_imdb.images.data, 4)
  %   sample = original_imdb.images.data(:,:,:,i);
  %   vectorized_sample = reshape(sample, 1, []);
  %   shuffled_sample = reshape(vectorized_sample(ix), size(sample, 1), size(sample, 2), size(sample, 3));
  %   original_imdb.images.data(:,:,:,i) = shuffled_sample;
  % end

  for i = 1 : numel(projection_string_list)
    projection_string = projection_string_list{i};
    afprintf(sprintf('[INFO] Testing experiment #%d / %d (projection_string: %s) ...', i, numel(projection_string_list), projection_string));


    experiment_options = {};
    if strfind(projection_string, 'larpV0P0RL0')
      experiment_options.imdb = original_imdb;
    elseif strfind(projection_string, 'pca')
      projected_dim = str2num(getStringParameterStartingAtIndex(projection_string, 18));
      experiment_options.imdb = fh_projection_utils.getPCAProjectedImdb(original_imdb, projected_dim);
    elseif strfind(projection_string, 'custom')
      larp_weight_init_type = 'gaussian-IdentityCovariance-MuDivide-1-SigmaDivide-1';
      experiment_options.imdb = getProjectedImdbUsingMatConvNet(original_imdb, dataset, larp_weight_init_type, projection_string, -1);
    elseif strfind(projection_string, 'densely-project-indep-row-into')
      experiment_options.imdb = getProjectedImdbSpecialFunction(original_imdb, projection_string, 'dense-gaussian-indep-row');
    elseif strfind(projection_string, 'densely-project-rotated-row-into')
      experiment_options.imdb = getProjectedImdbSpecialFunction(original_imdb, projection_string, 'dense-gaussian-rotated-row');
    elseif numel(strfind(projection_string, 'sparsely-project')) > 0 && numel(strfind(projection_string, 'indep-row-into')) > 0
      dim_kernel = str2num(getStringParameterStartingAtIndex(projection_string, 18));
      experiment_options.imdb = getProjectedImdbSpecialFunction(original_imdb, projection_string, sprintf('sparse-gaussian-%d-indep-row', dim_kernel));
    elseif numel(strfind(projection_string, 'sparsely-project')) > 0 && numel(strfind(projection_string, 'rotated-row-into')) > 0
      dim_kernel = str2num(getStringParameterStartingAtIndex(projection_string, 18));
      experiment_options.imdb = getProjectedImdbSpecialFunction(original_imdb, projection_string, sprintf('sparse-gaussian-%d-rotated-row', dim_kernel));
    else
      throwException('[ERROR] projection_string unrecognized.');
    end

    % a = experiment_options.imdb
    % keyboard

    experiment_options.dataset = dataset;
    experiment_options.posneg_balance = posneg_balance;
    experiment_options.experiment_parent_dir = experiment_dir;
    experiment_options.debug_flag = false;
    switch classification_method
      case '1-knn'
        experiment_options.number_of_nearest_neighbors = 1;
        performance = getSimpleTestAccuracyFromKnn(experiment_options);
      case '3-knn'
        experiment_options.number_of_nearest_neighbors = 3;
        performance = getSimpleTestAccuracyFromKnn(experiment_options);
      case 'c-sep'
        performance = getAverageClassCSeparation(experiment_options.imdb);
      case 'libsvm'
        performance = getSimpleTestAccuracyFromLibSvm(experiment_options);
      case 'mlp-64-10'
        experiment_options.number_of_hidden_nodes = [64, 10];
        performance = getSimpleTestAccuracyFromMLP(experiment_options);
      case 'mlp-500-100'
        experiment_options.number_of_hidden_nodes = [500, 100];
        performance = getSimpleTestAccuracyFromMLP(experiment_options);
      case 'mlp-500-1000-100'
        experiment_options.number_of_hidden_nodes = [500, 1000, 100];
        performance = getSimpleTestAccuracyFromMLP(experiment_options);
      case 'cnn'

        experiment_options.gpus = 3;

        % TODO: this has to somehow be detected automatically....
        % experiment_options.conv_network_arch = 'convV0P0RL0+fcV1-RF16CH64';
        % experiment_options.conv_network_arch = 'convV0P0RL0+fcV1-RF32CH64';

        % experiment_options.conv_network_arch = 'convV1P1RL1-RF32CH3+fcV1-RF16CH64';
        % experiment_options.conv_network_arch = 'convV3P1RL3-RF32CH3+fcV1-RF16CH64';
        % experiment_options.conv_network_arch = 'convV5P1RL5-RF32CH3+fcV1-RF16CH64';

        % experiment_options.conv_network_arch = 'convV1P0RL1-RF32CH3+fcV1-RF32CH64';
        % experiment_options.conv_network_arch = 'convV3P0RL3-RF32CH3+fcV1-RF32CH64';
        % experiment_options.conv_network_arch = 'convV5P0RL5-RF32CH3+fcV1-RF32CH64';

        % experiment_options.conv_network_arch = 'convV3P3RL3-RF32CH3+fcV1-RF4CH64-input64x64x3';
        experiment_options.conv_network_arch = 'convV3P3RL3-RF32CH3+fcV1-RF4CH64-input64x64x3-with-dropout';
        % experiment_options.conv_network_arch = 'convV5P3RL5-input64x64x3';

        [best_test_accuracy_mean, best_test_accuracy_std] = getSimpleTestAccuracyFromCnn(experiment_options);
        performance = best_test_accuracy_mean;
    end
    experiments{i}.performance = performance;
    afprintf(sprintf('[INFO] done!\n'));
  end

  all_experiments_single_run = experiments;



% -------------------------------------------------------------------------
function projected_imdb = getProjectedImdbSpecialFunction(original_imdb, projection_string, projection_layer_type)
% -------------------------------------------------------------------------
  fh_projection_utils = projectionUtils;
  index_offset = strfind(projection_string, '-into-') + 6;
  projected_dim = str2num(getStringParameterStartingAtIndex(projection_string, index_offset));
  number_in_ensemble = str2num(getStringParameterStartingAtIndex(projection_string, index_offset + length(num2str(projected_dim)) + 10));
  if strfind(projection_string, 'relu')
    projected_imdb = fh_projection_utils.getEnsembleDenselyDownProjectedImdb(original_imdb, 1, projection_layer_type, 1, 'relu', projected_dim, number_in_ensemble);
  elseif strfind(projection_string, 'vector-max-pool')
    % projected_imdb = fh_projection_utils.getEnsembleDenselyDownProjectedImdb(original_imdb, 1, projection_layer_type, 1, 'pooling-max-vector-width-9-stride-1', projected_dim, number_in_ensemble);
    % projected_imdb = fh_projection_utils.getEnsembleDenselyDownProjectedImdb(original_imdb, 1, projection_layer_type, 1, 'pooling-max-vector-width-9-stride-4', projected_dim, number_in_ensemble);
    projected_imdb = fh_projection_utils.getEnsembleDenselyDownProjectedImdb(original_imdb, 1, projection_layer_type, 1, 'pooling-max-vector-width-4-stride-4', projected_dim, number_in_ensemble);
    % projected_imdb = fh_projection_utils.getEnsembleDenselyDownProjectedImdb(original_imdb, 2, projection_layer_type, 2, 'pooling-max-vector-width-4-stride-4', projected_dim, number_in_ensemble);
    % projected_imdb = fh_projection_utils.getEnsembleDenselyDownProjectedImdb(original_imdb, 1, projection_layer_type, 1, 'pooling-max-vector-width-16-stride-16', projected_dim, number_in_ensemble);
    % projected_imdb = fh_projection_utils.getEnsembleDenselyDownProjectedImdb(original_imdb, 1, projection_layer_type, 1, 'pooling-max-vector-width-25-stride-25', projected_dim, number_in_ensemble);
  elseif strfind(projection_string, 'vector-min-pool')
    projected_imdb = fh_projection_utils.getEnsembleDenselyDownProjectedImdb(original_imdb, 1, projection_layer_type, 1, 'pooling-min-vector-width-4-stride-4', projected_dim, number_in_ensemble);
    % projected_imdb = fh_projection_utils.getEnsembleDenselyDownProjectedImdb(original_imdb, 1, projection_layer_type, 1, 'pooling-min-vector-width-16-stride-16', projected_dim, number_in_ensemble);
  elseif strfind(projection_string, 'vector-avg-pool')
    projected_imdb = fh_projection_utils.getEnsembleDenselyDownProjectedImdb(original_imdb, 1, projection_layer_type, 1, 'pooling-avg-vector-width-4-stride-4', projected_dim, number_in_ensemble);
  elseif strfind(projection_string, 'vl-nn-max-pool')
    projected_imdb = fh_projection_utils.getEnsembleDenselyDownProjectedImdb(original_imdb, 1, projection_layer_type, 1, 'pooling-max-2x2-stride-2-pad-0000', projected_dim, number_in_ensemble);
    % projected_imdb = fh_projection_utils.getEnsembleDenselyDownProjectedImdb(original_imdb, 1, projection_layer_type, 1, 'pooling-max-3x3-stride-2-pad-0101', projected_dim, number_in_ensemble);
  else
    projected_imdb = fh_projection_utils.getEnsembleDenselyDownProjectedImdb(original_imdb, 1, projection_layer_type, 0, 'whatever', projected_dim, number_in_ensemble);
  end



% -------------------------------------------------------------------------
function projected_imdb = getProjectedImdbUsingMatConvNet(original_imdb, dataset, larp_weight_init_type, larp_network_arch, projection_depth)
% -------------------------------------------------------------------------
  fh_projection_utils = projectionUtils;
  larp_weight_init_sequence = getLarpWeightInitSequence(larp_weight_init_type, larp_network_arch);
  projection_net = fh_projection_utils.getProjectionNetworkObject(dataset, larp_network_arch, larp_weight_init_sequence);
  projected_imdb = fh_projection_utils.projectImdbThroughNetwork(original_imdb, projection_net, projection_depth);


% -------------------------------------------------------------------------
function projection_string_list = getProjectionList()
% -------------------------------------------------------------------------
  projection_string_list = { ...
    ...
    ... 'larpV0P0RL0', ...
    ...
    ...
    ...
    ...
    ...
    ... ... % studying succession. part 1                                                      ... run 1 (avg 10) ... run 2 (avg 30) ... run 3 (avg 30)
    ... ... % 1) no observable difference between `vector-max-pool` and `vl-nn-max-pool`
    ... ... % 2) very little observable difference between (dense-indep-row, sparse-indep-row) & (dense-rotated-row, sparse-rotated-row) pairs, interesting!
    ... ... % 3) indep rows perform better when no pooling is present, and rotated rows perform better in presence of pooling, interesting!
    ... ... % 4) toeplitz-sparse implementation and matconvnet-sparse implementation return similar results, as expected.
    ... ... % 5) in matconvnet-sparse implementation, larger kernel sizes perform better, and with smaller variance, as expected.
    ... ...
    ... ...
    ... ... 'larpV0P0RL0', ... % 784                                                           ... {98.31}{00.00} ... {98.31}{00.00}
    ... ...
    ... ... 'densely-project-indep-row-into-784-ensemble-1', ... % 784                         ... {97.84}{00.36} ... {98.13}{00.18} ... {98.15}{00.19}
    ... ... 'densely-project-rotated-row-into-784-ensemble-1', ... % 784                       ...*{88.85}{02.37}*... {97.95}{00.54} ... {98.11}{00.39}
    ... ... 'sparsely-project-3-indep-row-into-784-ensemble-1', ... % 784                      ... {97.80}{00.35} ... {98.03}{00.41}
    ... ... 'sparsely-project-3-rotated-row-into-784-ensemble-1', ... % 784                    ... {97.06}{01.59} ... {96.48}{03.00}
    ... ...
    ... ... 'densely-project-indep-row-into-196-ensemble-1', ... % 196                         ... {97.81}{00.22} ... {97.89}{00.30} ... {97.84}{00.39}
    ... ... 'densely-project-rotated-row-into-196-ensemble-1', ... % 196                       ... {90.59}{01.80} ... {90.51}{01.93} ... {90.90}{02.08}
    ... ...
    ... ... 'densely-project-indep-row-into-784-ensemble-1-vector-max-pool', ... % 196         ... {96.94}{00.51} ... {96.99}{00.54}
    ... ... 'densely-project-rotated-row-into-784-ensemble-1-vector-max-pool', ... % 196       ... {97.88}{00.55} ... {97.80}{00.61}
    ... ... 'sparsely-project-3-indep-row-into-784-ensemble-1-vector-max-pool', ... % 196      ... {95.05}{01.17} ... {95.16}{00.99}
    ... ... 'sparsely-project-3-rotated-row-into-784-ensemble-1-vector-max-pool', ... % 196    ... {97.30}{01.13} ... {97.18}{01.08}
    ... ...
    ... ... 'densely-project-indep-row-into-784-ensemble-1-vl-nn-max-pool', ... % 196          ... {97.16}{00.40} ... {97.10}{00.29}
    ... ... 'densely-project-rotated-row-into-784-ensemble-1-vl-nn-max-pool', ... % 196        ... {97.74}{00.68} ... {97.82}{00.53}
    ... ... 'sparsely-project-3-indep-row-into-784-ensemble-1-vl-nn-max-pool', ... % 196       ... {95.17}{00.84} ... {95.32}{00.88}
    ... ... 'sparsely-project-3-rotated-row-into-784-ensemble-1-vl-nn-max-pool', ... % 196     ... {96.12}{03.45} ... {96.28}{02.94}
    ... ...
    ... ... 'custom-1-L-55-99-1-max-pool', ... % 196 (55 is 28*2-1, just like 63 was 32*2-1)   ... {97.87}{00.58} ... {97.71}{00.45} ... {97.80}{00.52}
    ... ... 'custom-1-L-3-99-1-max-pool', ... % 196                                            ... {95.68}{03.45} ... {97.38}{01.56} ... {95.55}{03.06}
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... % studying succession. part 2                                                      ... run 1 (avg 10) ... run 2 (avg 30) ... run 3 (avg 30)
    ... 'larpV0P0RL0', ... % 784                                                           ... {98.31}{00.00} ... the data itself
    ... 'densely-project-indep-row-into-784-ensemble-1', ... % 784                         ... {98.18}{00.16} ... compared to above, this is RP theory                                   [expect slight drop in perf]
    ... 'sparsely-project-3-indep-row-into-784-ensemble-1', ... % 784                      ... {97.89}{00.38} ... compared to above, we're studying structural sparsity                  [expect slight drop in perf]
    ... 'sparsely-project-3-rotated-row-into-784-ensemble-1', ... % 784                    ... {95.81}{04.45} ... compared to above, we're studying indep vs rotated rows                [expect slight drop in perf]
    ... 'sparsely-project-3-rotated-row-into-784-ensemble-4-vector-max-pool', ... % 784    ... {98.61}{00.48} ... compared to above, we're now introducing pooling                       [expect equal above]
    ... 'sparsely-project-3-rotated-row-into-784-ensemble-4-vl-nn-max-pool', ... % 784     ... {98.04}{00.96} ... compared to above, another version of pooling                          [expect equal above]
    ... 'custom-1-L-3-99-4-max-pool', ... % 784                                            ... {98.15}{00.89} ... compared to above, we're studying toeplitz-sparse vs matconvnet-sparse [expect equal above]
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... % EXPERIMENT: assert my toeplitz-sparse and matconvnet-sparse are equal in performance (MNIST-784-TWO-CLASS-5-0-BALANCED-100)
    ...
    ... % OBSERVATIONS
    ... %     #1) toeplitz-sparse = matconvnet-sparse ALWAYS! (it becomes apparent when setting kernels to all 1s and no pooling, and also becomes apparent with kernels = random w/ or w/o pooling).
    ... %     #2) ONLY when setting kernels to all 1s, BUT NOT when kernels are random, it becomes apparent that vl-nn-max-pool > vector-max-pool.. even on MNIST (which we're testing on) which is a somewhat non-conv dataset.
    ... %     #3) ONLY when setting kernels to all 1s, BUT NOT when kernels are random, having overlapping pooling kills perf.
    ... %     #4) Similar results seen on kernel dim = {3, 7}
    ...
    ... % RESULTS
    ...                                                                                                             % run 1 (avg 15)           run 2 (avg 15)
    ...                                                                                                             % kernels all ones         kernels randn / 10000
    ...
    ... %== == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
    ...
    ... % KERNEL DIM = 3 x 3
    ...
    ... 'sparsely-project-3-rotated-row-into-784-ensemble-1'                          % proj dim  = 784             % {98.65}{00.00}           {97.30}{01.44}
    ... 'custom-1-L-3-99-1'                                                           % proj dim  = 784             % {98.65}{00.00}           {96.79}{03.08}
    ...
    ... 'sparsely-project-3-rotated-row-into-784-ensemble-4'                          % proj dim  = 784 * 4         % {98.65}{00.00}           {97.91}{00.72}
    ... 'custom-1-L-3-99-4'                                                           % proj dim  = 784 * 4         % {98.65}{00.00}           {98.03}{00.86}
    ...
    ...
    ... % 'sparsely-project-3-rotated-row-into-784-ensemble-1-vector-max-pool' %9x4   % proj dim  = 784 / 4         % {94.05}{00.00}           {94.94}{01.31}
    ... % 'sparsely-project-3-rotated-row-into-784-ensemble-1-vl-nn-max-pool'  %9x4   % proj dim  = 784 / 4         % {97.98}{00.00}           {95.83}{02.68}
    ... 'sparsely-project-3-rotated-row-into-784-ensemble-1-vector-max-pool' %4x4     % proj dim  = 784 / 4         % {97.75}{00.00}           {97.08}{01.33}
    ... 'sparsely-project-3-rotated-row-into-784-ensemble-1-vl-nn-max-pool'  %4x4     % proj dim  = 784 / 4         % {98.59}{00.00}           {94.62}{03.68}
    ... 'custom-1-L-3-99-1-max-pool'                                       %4x4       % proj dim  = 784 / 4         % {98.59}{00.00}           {96.99}{02.00}
    ... ...
    ... % 'sparsely-project-3-rotated-row-into-784-ensemble-4-vector-max-pool' %9x4   % proj dim  = 784             % {94.05}{00.00}           {97.42}{01.21}
    ... % 'sparsely-project-3-rotated-row-into-784-ensemble-4-vl-nn-max-pool'  %9x4   % proj dim  = 784             % {97.98}{00.00}           {98.20}{00.75}
    ... 'sparsely-project-3-rotated-row-into-784-ensemble-4-vector-max-pool' %4x4     % proj dim  = 784             % {97.75}{00.00}           {98.65}{00.32}
    ... 'sparsely-project-3-rotated-row-into-784-ensemble-4-vl-nn-max-pool'  %4x4     % proj dim  = 784             % {98.59}{00.00}           {97.96}{00.98}
    ... 'custom-1-L-3-99-4-max-pool'                                       %4x4       % proj dim  = 784             % {98.59}{00.00}           {98.13}{01.21}
    ...
    ...
    ... %== == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
    ...
    ... % KERNEL DIM = 7 x 7
    ...
    ... 'sparsely-project-3-rotated-row-into-784-ensemble-1'                          % proj dim  = 784             % {97.53}{00.00}           {97.43}{01.06}
    ... 'custom-1-L-7-99-1'                                                           % proj dim  = 784             % {97.53}{00.00}           {96.84}{01.74}
    ...
    ... 'sparsely-project-3-rotated-row-into-784-ensemble-4'                          % proj dim  = 784 * 4         % {97.53}{00.00}           {97.88}{00.52}
    ... 'custom-1-L-7-99-4'                                                           % proj dim  = 784 * 4         % {97.53}{00.00}           {97.66}{00.55}
    ...
    ...
    ... % 'sparsely-project-3-rotated-row-into-784-ensemble-1-vector-max-pool' %9x4   % proj dim  = 784 / 4         % {91.36}{00.00}           {96.32}{00.97}
    ... % 'sparsely-project-3-rotated-row-into-784-ensemble-1-vl-nn-max-pool'  %9x4   % proj dim  = 784 / 4         % {96.46}{00.00}           {97.50}{01.33}
    ... 'sparsely-project-3-rotated-row-into-784-ensemble-1-vector-max-pool' %4x4     % proj dim  = 784 / 4         % {96.24}{00.00}           {97.57}{00.96}
    ... 'sparsely-project-3-rotated-row-into-784-ensemble-1-vl-nn-max-pool'  %4x4     % proj dim  = 784 / 4         % {97.08}{00.00}           {96.80}{02.56}
    ... 'custom-1-L-7-99-1-max-pool'                                       %4x4       % proj dim  = 784 / 4         % {97.08}{00.00}           {97.58}{00.87}
    ...
    ... % 'sparsely-project-3-rotated-row-into-784-ensemble-4-vector-max-pool' %9x4   % proj dim  = 784             % {91.36}{00.00}           {98.23}{00.43}
    ... % 'sparsely-project-3-rotated-row-into-784-ensemble-4-vl-nn-max-pool'  %9x4   % proj dim  = 784             % {96.46}{00.00}           {98.58}{00.29}
    ... 'sparsely-project-3-rotated-row-into-784-ensemble-4-vector-max-pool' %4x4     % proj dim  = 784             % {96.24}{00.00}           {98.74}{00.29}
    ... 'sparsely-project-3-rotated-row-into-784-ensemble-4-vl-nn-max-pool'  %4x4     % proj dim  = 784             % {97.08}{00.00}           {97.85}{00.74}
    ... 'custom-1-L-7-99-4-max-pool'                                       %4x4       % proj dim  = 784             % {97.08}{00.00}           {98.02}{00.35}
    ...
    ...
    ... %== == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... % EXPERIMENT: study effect of structural sparsity & indep vs rotated rows (study succession WITHOUT pooling.)
    ... %             study the progression of dense RP towards sparse RP (w/ smaller and smaller kernel size)
    ...
    ... % OBSERVATIONS:
    ... %     #1) w/o pooling indep rows is ALWAYS > rotated rows... BUT
    ... %     #2) w   pooling indep rows is ALWAYS < rotated rows...
    ... %     #3) vector-max-pool == vl-nn-max-pool... can't really see any difference
    ... % MAYBE STRUCTURAL SPARSITY IS NOT IMPORTANT AT ALL... SEE HOW BEST DENSE = BEST SPARSE
    ...
    ...
    ... %     #4) dense is NOT equal to sparse w/ dim_kernel = 55, because of padding...
    ...
    ...
    ... %     #5) scalar times randn does not affect perf (expected, because all the space is being scaled together doesn't affect 1-NN)
    ...
    ...
    ... %     #6) for indep rows,   going from dim_kernel = 55 to dim_kernel = 1 leads to a decrease in perf
    ... %     #7) for rotated rows, going from dim_kernel = 55 to dim_kernel = 3 leads to a decrease in perf, but then jumps up for dim_kernel = 1 (well because it's getting multiplied by identity, so gives same perf as initial).
    ... %     #8) reducing dim_kernel increases variance of results (expected, becuase more variance in pixels being linearly summed over)
    ...
    ...
    ...
    ... % RESULTS
    ...                                                                                                                            % run 1 (avg 3)            run 2 (avg 30)                run 3 (avg 30)                run 4 (avg 30)
    ...                                                                                                                            % kernels all ones         kernels randn / 10000         kernels randn / 100           kernels randn / 1
    ...
    ... %== == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
    ...
    ... % MNIST-784-TWO-CLASS-5-0-BALANCED-100
    ...
    ... 'larpV0P0RL0', ...                                                                               % proj dim: 784           % {98.31}{00.00} ***       {98.31}{00.00} ***            {98.31}{00.00} ***            {98.31}{00.00} ***
    ...
    ... 'densely-project-indep-row-into-784-ensemble-1', ...                                             % proj dim: 784           % {97.96}{00.00}           {98.15}{00.18}                {98.17}{00.19}                {98.26}{00.20}
    ... 'densely-project-rotated-row-into-784-ensemble-1', ...                                           % proj dim: 784           % {97.81}{00.00}           {97.81}{00.60}                {97.75}{00.59}                {97.78}{00.44}
    ...
    ... 'sparsely-project-55-indep-row-into-784-ensemble-1', ...                     % 55x55 kernels     % proj dim: 784           % {58.57}{00.00}           {98.16}{00.20}                {98.18}{00.17}                {98.23}{00.17}
    ... 'sparsely-project-55-rotated-row-into-784-ensemble-1', ...                   % 55x55 kernels     % proj dim: 784           % {58.57}{00.00}           {97.81}{00.49}                {98.02}{00.42}                {97.87}{00.54}
    ...
    ... 'sparsely-project-25-indep-row-into-784-ensemble-1', ...                     % 25x25 kernels     % proj dim: 784           % {86.26}{00.00}           {98.38}{00.19}                {98.38}{00.18}                {98.32}{00.19}
    ... 'sparsely-project-25-rotated-row-into-784-ensemble-1', ...                   % 25x25 kernels     % proj dim: 784           % {86.26}{00.00}           {98.10}{00.34}                {98.01}{00.43}                {97.98}{00.54}
    ...
    ... 'sparsely-project-11-indep-row-into-784-ensemble-1', ...                     % 11x11 kernels     % proj dim: 784           % {93.38}{00.00}           {98.15}{00.20}                {98.03}{00.16}                {98.17}{00.24}
    ... 'sparsely-project-11-rotated-row-into-784-ensemble-1', ...                   % 11x11 kernels     % proj dim: 784           % {93.38}{00.00}           {97.55}{01.02}                {97.56}{01.08}                {97.55}{01.09}
    ...
    ... 'sparsely-project-3-indep-row-into-784-ensemble-1', ...                      % 3x3 kernels       % proj dim: 784           % {98.65}{00.00}           {97.78}{00.40}                {97.92}{00.37}                {97.92}{00.45}
    ... 'sparsely-project-3-rotated-row-into-784-ensemble-1', ...                    % 3x3 kernels       % proj dim: 784           % {98.65}{00.00}           {96.33}{03.71}                {96.48}{02.81}                {96.77}{03.37}
    ...
    ... 'sparsely-project-1-indep-row-into-784-ensemble-1', ...                      % 1x1 kernels       % proj dim: 784           % {98.31}{00.00}           {97.57}{00.59}                {97.54}{00.47}                {97.54}{00.62}
    ... 'sparsely-project-1-rotated-row-into-784-ensemble-1', ...                    % 1x1 kernels = EYE % proj dim: 784           % {98.31}{00.00} ***       {98.31}{00.00} ***            {98.31}{00.00} ***            {98.31}{00.00} ***
    ...
    ... %== == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
    ...
    ... % MNIST-784-TWO-CLASS-5-0-BALANCED-100 w/ vector-max-pool
    ...
    ... 'larpV0P0RL0', ...                                                                               % proj dim: 784                                                                                                  {98.31}{00.00} ***
    ...
    ... 'densely-project-indep-row-into-784-ensemble-4-vector-max-pool', ...                             % proj dim: 784                                                                                                  {97.75}{00.23}
    ... 'densely-project-rotated-row-into-784-ensemble-4-vector-max-pool', ...                           % proj dim: 784                                                                                                  {98.52}{00.24} >>>
    ...
    ... 'sparsely-project-55-indep-row-into-784-ensemble-4-vector-max-pool', ...     % 55x55 kernels     % proj dim: 784                                                                                                  {97.75}{00.22}
    ... 'sparsely-project-55-rotated-row-into-784-ensemble-4-vector-max-pool', ...   % 55x55 kernels     % proj dim: 784                                                                                                  {98.57}{00.23}
    ...
    ... 'sparsely-project-25-indep-row-into-784-ensemble-4-vector-max-pool', ...     % 25x25 kernels     % proj dim: 784                                                                                                  {98.06}{00.22}
    ... 'sparsely-project-25-rotated-row-into-784-ensemble-4-vector-max-pool', ...   % 25x25 kernels     % proj dim: 784                                                                                                  {98.79}{00.19}
    ...
    ... 'sparsely-project-11-indep-row-into-784-ensemble-4-vector-max-pool', ...     % 11x11 kernels     % proj dim: 784                                                                                                  {97.81}{00.26}
    ... 'sparsely-project-11-rotated-row-into-784-ensemble-4-vector-max-pool', ...   % 11x11 kernels     % proj dim: 784                                                                                                  {98.55}{00.35}
    ...
    ... 'sparsely-project-3-indep-row-into-784-ensemble-4-vector-max-pool', ...      % 3x3 kernels       % proj dim: 784                                                                                                  {97.08}{00.43}
    ... 'sparsely-project-3-rotated-row-into-784-ensemble-4-vector-max-pool', ...    % 3x3 kernels       % proj dim: 784                                                                                                  {98.79}{00.30}
    ...
    ... 'sparsely-project-1-indep-row-into-784-ensemble-4-vector-max-pool', ...      % 1x1 kernels       % proj dim: 784                                                                                                  {96.43}{00.73}
    ... 'sparsely-project-1-rotated-row-into-784-ensemble-4-vector-max-pool', ...    % 1x1 kernels = EYE % proj dim: 784                                                                                                  {97.54}{01.41} ***
    ...
    ... %== == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
    ...
    ... % MNIST-784-TWO-CLASS-5-0-BALANCED-100 w/ vl-nn-max-pool
    ...
    ... 'larpV0P0RL0', ...                                                                               % proj dim: 784                                                                                                  {98.31}{00.00} ***
    ...
    ... 'densely-project-indep-row-into-784-ensemble-4-vl-nn-max-pool', ...                              % proj dim: 784                                                                                                  {97.85}{00.26}
    ... 'densely-project-rotated-row-into-784-ensemble-4-vl-nn-max-pool', ...                            % proj dim: 784                                                                                                  {98.27}{00.21}
    ...
    ... 'sparsely-project-55-indep-row-into-784-ensemble-4-vl-nn-max-pool', ...      % 55x55 kernels     % proj dim: 784                                                                                                  {97.66}{00.28}
    ... 'sparsely-project-55-rotated-row-into-784-ensemble-4-vl-nn-max-pool', ...    % 55x55 kernels     % proj dim: 784                                                                                                  {98.26}{00.25}
    ...
    ... 'sparsely-project-25-indep-row-into-784-ensemble-4-vl-nn-max-pool', ...      % 25x25 kernels     % proj dim: 784                                                                                                  {97.99}{00.22}
    ... 'sparsely-project-25-rotated-row-into-784-ensemble-4-vl-nn-max-pool', ...    % 25x25 kernels     % proj dim: 784                                                                                                  {98.36}{00.27}
    ...
    ... 'sparsely-project-11-indep-row-into-784-ensemble-4-vl-nn-max-pool', ...      % 11x11 kernels     % proj dim: 784                                                                                                  {97.84}{00.23}
    ... 'sparsely-project-11-rotated-row-into-784-ensemble-4-vl-nn-max-pool', ...    % 11x11 kernels     % proj dim: 784                                                                                                  {98.21}{00.50}
    ...
    ... 'sparsely-project-3-indep-row-into-784-ensemble-4-vl-nn-max-pool', ...       % 3x3 kernels       % proj dim: 784                                                                                                  {97.26}{00.45}
    ... 'sparsely-project-3-rotated-row-into-784-ensemble-4-vl-nn-max-pool', ...     % 3x3 kernels       % proj dim: 784                                                                                                  {98.19}{00.81}
    ...
    ... 'sparsely-project-1-indep-row-into-784-ensemble-4-vl-nn-max-pool', ...       % 1x1 kernels       % proj dim: 784                                                                                                  {96.66}{00.59}
    ... 'sparsely-project-1-rotated-row-into-784-ensemble-4-vl-nn-max-pool', ...     % 1x1 kernels = EYE % proj dim: 784                                                                                                  {97.61}{01.99} ***
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... %== == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
    ...
    ... % MNIST-784-BALANCED-250
    ...
    ... 'larpV0P0RL0', ...                                                                               % proj dim: 784                                                                                                {92.01}{00.00}
    ...
    ... 'densely-project-indep-row-into-784-ensemble-1', ...                                             % proj dim: 784                                                                                                {91.73}{00.15}
    ... 'densely-project-rotated-row-into-784-ensemble-1', ...                                           % proj dim: 784                                                                                                {91.12}{00.61}
    ...
    ... 'densely-project-indep-row-into-784-ensemble-4-vector-max-pool', ...                             % proj dim: 784                                                                                                {91.12}{00.17}
    ... 'densely-project-rotated-row-into-784-ensemble-4-vector-max-pool', ...                           % proj dim: 784                                                                                                {92.05}{00.29} >>>
    ... ...
    ... 'densely-project-indep-row-into-784-ensemble-4-vl-nn-max-pool', ...                              % proj dim: 784                                                                                                {91.09}{00.16}
    ... 'densely-project-rotated-row-into-784-ensemble-4-vl-nn-max-pool', ...                            % proj dim: 784                                                                                                {92.31}{00.31} >>>
    ...
    ... %== == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... %== == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
    ...
    ... % MNIST-FASHION-BALANCED-250
    ...
    ... 'larpV0P0RL0', ...                                                                               % proj dim: 784                                                                                                {--.--}{--.--}
    ... ...
    ... 'pca-project-into-64', ...                                                                      % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'pca-project-into-128', ...                                                                      % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'pca-project-into-256', ...                                                                      % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'pca-project-into-512', ...                                                                      % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'pca-project-into-784', ...                                                                      % proj dim: 784                                                                                                {--.--}{--.--}
    ... ...
    ... 'densely-project-indep-row-into-64-ensemble-1', ...                                             % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'densely-project-indep-row-into-128-ensemble-1', ...                                             % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'densely-project-indep-row-into-256-ensemble-1', ...                                             % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'densely-project-indep-row-into-512-ensemble-1', ...                                             % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'densely-project-indep-row-into-784-ensemble-1', ...                                             % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'densely-project-rotated-row-into-64-ensemble-1', ...                                           % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'densely-project-rotated-row-into-128-ensemble-1', ...                                           % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'densely-project-rotated-row-into-256-ensemble-1', ...                                           % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'densely-project-rotated-row-into-512-ensemble-1', ...                                           % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'densely-project-rotated-row-into-784-ensemble-1', ...                                           % proj dim: 784                                                                                                {--.--}{--.--}
    ... ...
    ... 'densely-project-indep-row-into-64-ensemble-1-relu', ...                                        % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'densely-project-indep-row-into-128-ensemble-1-relu', ...                                        % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'densely-project-indep-row-into-256-ensemble-1-relu', ...                                        % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'densely-project-indep-row-into-512-ensemble-1-relu', ...                                        % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'densely-project-indep-row-into-784-ensemble-1-relu', ...                                        % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'densely-project-rotated-row-into-64-ensemble-1-relu', ...                                      % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'densely-project-rotated-row-into-128-ensemble-1-relu', ...                                      % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'densely-project-rotated-row-into-256-ensemble-1-relu', ...                                      % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'densely-project-rotated-row-into-512-ensemble-1-relu', ...                                      % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'densely-project-rotated-row-into-784-ensemble-1-relu', ...                                      % proj dim: 784                                                                                                {--.--}{--.--}
    ... ...
    ... 'densely-project-indep-row-into-64-ensemble-4-vector-max-pool', ...                             % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'densely-project-indep-row-into-128-ensemble-4-vector-max-pool', ...                             % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'densely-project-indep-row-into-256-ensemble-4-vector-max-pool', ...                             % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'densely-project-indep-row-into-512-ensemble-4-vector-max-pool', ...                             % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'densely-project-indep-row-into-784-ensemble-4-vector-max-pool', ...                             % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'densely-project-rotated-row-into-64-ensemble-4-vector-max-pool', ...                           % proj dim: 784                                                                                                {--.--}{--.--} >>>
    ... 'densely-project-rotated-row-into-128-ensemble-4-vector-max-pool', ...                           % proj dim: 784                                                                                                {--.--}{--.--} >>>
    ... 'densely-project-rotated-row-into-256-ensemble-4-vector-max-pool', ...                           % proj dim: 784                                                                                                {--.--}{--.--} >>>
    ... 'densely-project-rotated-row-into-512-ensemble-4-vector-max-pool', ...                           % proj dim: 784                                                                                                {--.--}{--.--} >>>
    ... 'densely-project-rotated-row-into-784-ensemble-4-vector-max-pool', ...                           % proj dim: 784                                                                                                {--.--}{--.--} >>>
    ... ...
    ... ... 'sparsely-project-3-indep-row-into-64-ensemble-4-vector-max-pool', ...                             % proj dim: 784                                                                                                {--.--}{--.--}
    ... ... 'sparsely-project-3-indep-row-into-128-ensemble-4-vector-max-pool', ...                             % proj dim: 784                                                                                                {--.--}{--.--}
    ... ... 'sparsely-project-3-indep-row-into-256-ensemble-4-vector-max-pool', ...                             % proj dim: 784                                                                                                {--.--}{--.--}
    ... ... 'sparsely-project-3-indep-row-into-512-ensemble-4-vector-max-pool', ...                             % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'sparsely-project-3-indep-row-into-784-ensemble-1-vector-max-pool', ...                             % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'sparsely-project-3-indep-row-into-784-ensemble-2-vector-max-pool', ...                             % proj dim: 784                                                                                                {--.--}{--.--}
    ... 'sparsely-project-3-indep-row-into-784-ensemble-4-vector-max-pool', ...                             % proj dim: 784                                                                                                {--.--}{--.--}
    ... ... 'sparsely-project-3-rotated-row-into-64-ensemble-4-vector-max-pool', ...                           % proj dim: 784                                                                                                {--.--}{--.--} >>>
    ... ... 'sparsely-project-3-rotated-row-into-128-ensemble-4-vector-max-pool', ...                           % proj dim: 784                                                                                                {--.--}{--.--} >>>
    ... ... 'sparsely-project-3-rotated-row-into-256-ensemble-4-vector-max-pool', ...                           % proj dim: 784                                                                                                {--.--}{--.--} >>>
    ... ... 'sparsely-project-3-rotated-row-into-512-ensemble-4-vector-max-pool', ...                           % proj dim: 784                                                                                                {--.--}{--.--} >>>
    ... 'sparsely-project-3-rotated-row-into-784-ensemble-1-vector-max-pool', ...                           % proj dim: 784                                                                                                {--.--}{--.--} >>>
    ... 'sparsely-project-3-rotated-row-into-784-ensemble-2-vector-max-pool', ...                           % proj dim: 784                                                                                                {--.--}{--.--} >>>
    ... 'sparsely-project-3-rotated-row-into-784-ensemble-4-vector-max-pool', ...                           % proj dim: 784                                                                                                {--.--}{--.--} >>>
    ... ...
    ... ... 'densely-project-indep-row-into-784-ensemble-4-vl-nn-max-pool', ...                              % proj dim: 784                                                                                                {--.--}{--.--}
    ... ... 'densely-project-rotated-row-into-784-ensemble-4-vl-nn-max-pool', ...                            % proj dim: 784                                                                                                {--.--}{--.--} >>>
    ...
    ... %== == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... %== == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
    ...
    ... % CIFAR-NO-WHITE-TWO-CLASS-DEER-TRUCK-BALANCED-100
    ...
    ... 'larpV0P0RL0', ...                                                                               % proj dim: 3072                                                                                                 {77.25}{00.00}
    ... ...
    ... 'densely-project-indep-row-into-3072-ensemble-1', ...                                            % proj dim: 3072                                                                                                 {77.16}{00.40}
    ... 'densely-project-rotated-row-into-3072-ensemble-1', ...                                          % proj dim: 3072                                                                                                 {75.79}{01.68}
    ... ...
    ... 'densely-project-indep-row-into-3072-ensemble-4-vector-max-pool', ...                            % proj dim: 3072                                                                                                 {78.79}{00.48} >>>
    ... 'densely-project-rotated-row-into-3072-ensemble-4-vector-max-pool', ...                          % proj dim: 3072                                                                                                 {77.92}{01.02} >>>
    ... ... ...
    ... ... 'densely-project-indep-row-into-3072-ensemble-4-vl-nn-max-pool', ...                             % proj dim: 3072                                                                                                 {--.--}{--.--}
    ... ... 'densely-project-rotated-row-into-3072-ensemble-4-vl-nn-max-pool', ...                           % proj dim: 3072                                                                                                 {--.--}{--.--}
    ...
    ... %== == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... %== == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
    ...
    ... % CIFAR-NO-WHITE-BALANCED-250
    ...
    ... 'larpV0P0RL0', ...                                                                               % proj dim: 3072                                                                                                 {27.26}{00.00}
    ... ...
    ... 'densely-project-indep-row-into-3072-ensemble-1', ...                                            % proj dim: 3072                                                                                                 {27.10}{00.19}
    ... 'densely-project-rotated-row-into-3072-ensemble-1', ...                                          % proj dim: 3072                                                                                                 {25.56}{00.88}
    ... ...
    ... 'densely-project-indep-row-into-3072-ensemble-4-vector-max-pool', ...                            % proj dim: 3072                                                                                                 {29.61}{00.30} >>>
    ... 'densely-project-rotated-row-into-3072-ensemble-4-vector-max-pool', ...                          % proj dim: 3072                                                                                                 {28.62}{00.46} >>>
    ... ... ...
    ... ... 'densely-project-indep-row-into-3072-ensemble-4-vl-nn-max-pool', ...                             % proj dim: 3072                                                                                                 {--.--}{--.--}
    ... ... 'densely-project-rotated-row-into-3072-ensemble-4-vl-nn-max-pool', ...                           % proj dim: 3072                                                                                                 {--.--}{--.--}
    ...
    ...
    ...
    ...
    'larpV0P0RL0', ...
    ... ...
    'pca-project-into-64', ...
    'pca-project-into-128', ...
    'pca-project-into-256', ...
    'pca-project-into-512', ...
    'pca-project-into-1024', ...
    ... ...
    'densely-project-indep-row-into-64-ensemble-1', ...
    'densely-project-indep-row-into-128-ensemble-1', ...
    'densely-project-indep-row-into-256-ensemble-1', ...
    'densely-project-indep-row-into-512-ensemble-1', ...
    'densely-project-indep-row-into-1024-ensemble-1', ...
    'densely-project-rotated-row-into-64-ensemble-1', ...
    'densely-project-rotated-row-into-128-ensemble-1', ...
    'densely-project-rotated-row-into-256-ensemble-1', ...
    'densely-project-rotated-row-into-512-ensemble-1', ...
    'densely-project-rotated-row-into-1024-ensemble-1', ...
    ... ...
    'densely-project-indep-row-into-64-ensemble-1-relu', ...
    'densely-project-indep-row-into-128-ensemble-1-relu', ...
    'densely-project-indep-row-into-256-ensemble-1-relu', ...
    'densely-project-indep-row-into-512-ensemble-1-relu', ...
    'densely-project-indep-row-into-1024-ensemble-1-relu', ...
    'densely-project-rotated-row-into-64-ensemble-1-relu', ...
    'densely-project-rotated-row-into-128-ensemble-1-relu', ...
    'densely-project-rotated-row-into-256-ensemble-1-relu', ...
    'densely-project-rotated-row-into-512-ensemble-1-relu', ...
    'densely-project-rotated-row-into-1024-ensemble-1-relu', ...
    ... ...
    'densely-project-indep-row-into-64-ensemble-4-vector-max-pool', ...
    'densely-project-indep-row-into-128-ensemble-4-vector-max-pool', ...
    'densely-project-indep-row-into-256-ensemble-4-vector-max-pool', ...
    'densely-project-indep-row-into-512-ensemble-4-vector-max-pool', ...
    'densely-project-indep-row-into-1024-ensemble-4-vector-max-pool', ...
    'densely-project-rotated-row-into-64-ensemble-4-vector-max-pool', ...
    'densely-project-rotated-row-into-128-ensemble-4-vector-max-pool', ...
    'densely-project-rotated-row-into-256-ensemble-4-vector-max-pool', ...
    'densely-project-rotated-row-into-512-ensemble-4-vector-max-pool', ...
    'densely-project-rotated-row-into-1024-ensemble-4-vector-max-pool', ...
    ... ...
    'sparsely-project-3-indep-row-into-1024-ensemble-1-vector-max-pool', ...
    'sparsely-project-3-indep-row-into-1024-ensemble-2-vector-max-pool', ...
    'sparsely-project-3-indep-row-into-1024-ensemble-4-vector-max-pool', ...
    'sparsely-project-3-rotated-row-into-1024-ensemble-1-vector-max-pool', ...
    'sparsely-project-3-rotated-row-into-1024-ensemble-2-vector-max-pool', ...
    'sparsely-project-3-rotated-row-into-1024-ensemble-4-vector-max-pool', ...
    ... ...
    ...
    ...
    ... %== == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... %== == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
    ...
    ... % STL-10-BALANCED-250
    ...
    ... 'larpV0P0RL0', ...                                                                               % proj dim: 3072                                                                                                 {27.56}{00.00}
    ... ...
    ... 'densely-project-indep-row-into-3072-ensemble-1', ...                                            % proj dim: 3072                                                                                                 {27.64}{00.19} >>>
    ... 'densely-project-rotated-row-into-3072-ensemble-1', ...                                          % proj dim: 3072                                                                                                 {26.95}{01.39}
    ... ...
    ... 'densely-project-indep-row-into-3072-ensemble-4-vector-max-pool', ...                            % proj dim: 3072                                                                                                 {29.50}{00.23} >>>
    ... 'densely-project-rotated-row-into-3072-ensemble-4-vector-max-pool', ...                          % proj dim: 3072                                                                                                 {29.49}{01.22} >>>
    ... ... ...
    ... ... 'densely-project-indep-row-into-3072-ensemble-4-vl-nn-max-pool', ...                             % proj dim: 3072                                                                                                 {--.--}{--.--}
    ... ... 'densely-project-rotated-row-into-3072-ensemble-4-vl-nn-max-pool', ...                           % proj dim: 3072                                                                                                 {--.--}{--.--}
    ...
    ... %== == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... %== == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
    ...
    ... % SVHN-BALANCED-250
    ...
    ... 'larpV0P0RL0', ...                                                                               % proj dim: 3072                                                                                                 {32.58}{00.00}
    ... ...
    ... 'densely-project-indep-row-into-3072-ensemble-1', ...                                            % proj dim: 3072                                                                                                 {32.25}{00.19}
    ... 'densely-project-rotated-row-into-3072-ensemble-1', ...                                          % proj dim: 3072                                                                                                 {30.17}{02.72}
    ... ...
    ... 'densely-project-indep-row-into-3072-ensemble-4-vector-max-pool', ...                            % proj dim: 3072                                                                                                 {31.34}{00.16}
    ... 'densely-project-rotated-row-into-3072-ensemble-4-vector-max-pool', ...                          % proj dim: 3072                                                                                                 {31.12}{01.71}
    ... ... ...
    ... ... 'densely-project-indep-row-into-3072-ensemble-4-vl-nn-max-pool', ...                             % proj dim: 3072                                                                                                 {--.--}{--.--}
    ... ... 'densely-project-rotated-row-into-3072-ensemble-4-vl-nn-max-pool', ...                           % proj dim: 3072                                                                                                 {--.--}{--.--}
    ...
    ... %== == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... %== == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
    ...
    ... % IMAGE-NET-TINY-10-PAIRS-BALANCED-500
    ...
    ... 'larpV0P0RL0', ...                                                                               % proj dim: 3072                                                                                                 {--.--}{--.--}
    ... ...
    ... 'densely-project-indep-row-into-3072-ensemble-1', ...                                            % proj dim: 3072                                                                                                 {--.--}{--.--}
    ... 'densely-project-rotated-row-into-3072-ensemble-1', ...                                          % proj dim: 3072                                                                                                 {--.--}{--.--}
    ... ...
    ... 'densely-project-indep-row-into-3072-ensemble-4-vector-max-pool', ...                            % proj dim: 3072                                                                                                 {--.--}{--.--}
    ... 'densely-project-rotated-row-into-3072-ensemble-4-vector-max-pool', ...                          % proj dim: 3072                                                                                                 {--.--}{--.--}
    ... ... ...
    ... ... 'densely-project-indep-row-into-3072-ensemble-4-vl-nn-max-pool', ...                             % proj dim: 3072                                                                                                 {--.--}{--.--}
    ... ... 'densely-project-rotated-row-into-3072-ensemble-4-vl-nn-max-pool', ...                           % proj dim: 3072                                                                                                 {--.--}{--.--}
    ...
    ... %== == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... %== == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
    ...
    ... % UCI-GISETTE-BALANCED-WHATEVER
    ...
    ... 'larpV0P0RL0', ...                                                                               % proj dim: 5000                                                                                                 {96.20}{00.00}
    ... ...
    ... 'densely-project-indep-row-into-5000-ensemble-1', ...                                            % proj dim: 5000                                                                                                 {95.66}{00.33}
    ... 'densely-project-rotated-row-into-5000-ensemble-1', ...                                          % proj dim: 5000                                                                                                 {95.50}{00.44}
    ... ...
    ... 'densely-project-indep-row-into-5000-ensemble-4-vector-max-pool', ...                            % proj dim: 5000                                                                                                 {94.18}{00.33}
    ... 'densely-project-rotated-row-into-5000-ensemble-4-vector-max-pool', ...                          % proj dim: 5000                                                                                                 {93.54}{00.95}
    ... ... ...
    ... ... 'densely-project-indep-row-into-5000-ensemble-4-vl-nn-max-pool', ...                             % proj dim: 5000                                                                                                 {--.--}{--.--}
    ... ... 'densely-project-rotated-row-into-5000-ensemble-4-vl-nn-max-pool', ...                           % proj dim: 5000                                                                                                 {--.--}{--.--}
    ...
    ... %== == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == == ==
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... % EXPERIMENT: projecting into higher dimensions in hope of better 1-NN perf...
    ... % OBSERVATIONS: quickly plateaus... also higher dims suck!
    ... % RESULTS:
    ...
    ... 'larpV0P0RL0', ... % 784                                                   ... {98.31}{00.00}
    ... 'densely-project-indep-row-into-784-ensemble-1', ... % 784                 ... {98.17}{00.14}
    ... 'densely-project-indep-row-into-1024-ensemble-1', ... % 1024               ... {98.19}{00.19}
    ... 'densely-project-indep-row-into-2048-ensemble-1', ... % 2048               ... {98.23}{00.13}
    ... 'densely-project-indep-row-into-4096-ensemble-1', ... % 4096               ... {98.29}{00.10}
    ... 'densely-project-indep-row-into-8192-ensemble-1', ... % 8192               ... {98.29}{00.07}
    ... 'densely-project-indep-row-into-16384-ensemble-1', ... % 16384             ... {98.32}{00.07}
    ...
    ...
    ... 'larpV0P0RL0', ... % 3072                                                  ... {77.25}{00.00}
    ... 'densely-project-indep-row-into-3072-ensemble-1', ... % 3072               ... {77.09}{00.33}
    ... 'densely-project-indep-row-into-6144-ensemble-1', ... % 6144               ... {77.10}{00.25}
    ... 'densely-project-indep-row-into-4096-ensemble-1', ... % 4096               ... {77.18}{00.30}
    ... 'densely-project-indep-row-into-8192-ensemble-1', ... % 8192               ... {77.22}{00.28}
    ... 'densely-project-indep-row-into-8192-ensemble-1', ... % 8192               ... {77.26}{00.27}
    ... 'densely-project-indep-row-into-16384-ensemble-1', ... % 16384             ... {77.28}{00.19}
    ... 'densely-project-indep-row-into-16384-ensemble-1', ... % 16384             ... {77.27}{00.24}
    ... 'densely-project-indep-row-into-32768-ensemble-1', ... % 32768             ... {77.17}{00.16}
    ... 'densely-project-indep-row-into-32768-ensemble-1', ... % 32768             ... {77.26}{00.13}
    ... 'densely-project-indep-row-into-65536-ensemble-1', ... % 65536             ... {77.24}{00.19}
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... % ANYTHING-under-100
    ... 'pca-project-into-1', ...
    ... 'pca-project-into-2', ...
    ... 'pca-project-into-4', ...
    ... 'pca-project-into-8', ...
    ... 'pca-project-into-16', ...
    ... 'pca-project-into-32', ...
    ...
    ... 'densely-project-indep-row-into-1-ensemble-1', ...
    ... 'densely-project-indep-row-into-2-ensemble-1', ...
    ... 'densely-project-indep-row-into-4-ensemble-1', ...
    ... 'densely-project-indep-row-into-8-ensemble-1', ...
    ... 'densely-project-indep-row-into-16-ensemble-1', ...
    ... 'densely-project-indep-row-into-32-ensemble-1', ...
    ...
    ... 'densely-project-indep-row-into-4-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-8-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-16-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-32-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-64-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-128-ensemble-1-vector-max-pool', ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... % MNIST-784
    ... 'pca-project-into-1', ...
    ... 'pca-project-into-2', ...
    ... 'pca-project-into-4', ...
    ... 'pca-project-into-8', ...
    ... 'pca-project-into-16', ...
    ... 'pca-project-into-32', ...
    ... 'pca-project-into-64', ...
    ... 'pca-project-into-128', ...
    ... 'pca-project-into-256', ...
    ... 'pca-project-into-512', ...
    ... 'pca-project-into-784', ...
    ...
    ... 'densely-project-indep-row-into-1-ensemble-1', ...
    ... 'densely-project-indep-row-into-2-ensemble-1', ...
    ... 'densely-project-indep-row-into-4-ensemble-1', ...
    ... 'densely-project-indep-row-into-8-ensemble-1', ...
    ... 'densely-project-indep-row-into-16-ensemble-1', ...
    ... 'densely-project-indep-row-into-32-ensemble-1', ...
    ... 'densely-project-indep-row-into-64-ensemble-1', ...
    ... 'densely-project-indep-row-into-128-ensemble-1', ...
    ... 'densely-project-indep-row-into-256-ensemble-1', ...
    ... 'densely-project-indep-row-into-512-ensemble-1', ...
    ... 'densely-project-indep-row-into-784-ensemble-1', ...
    ...
    ... 'densely-project-indep-row-into-4-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-8-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-16-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-32-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-64-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-128-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-256-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-512-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-1024-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-2048-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-3136-ensemble-1-vector-max-pool', ...
    ...
    ...
    ...
    ...
    ...
    ... 'custom-1-L-3-99-1-max-pool', ... % 196
    ... 'custom-1-L-3-99-2-max-pool', ... % 392
    ... 'custom-1-L-3-99-4-max-pool', ... % 784
    ...
    ...
    ... 'custom-2-L-3-16-1-max-pool', ... % 49
    ... 'custom-2-L-3-16-2-max-pool', ... % 98
    ... 'custom-2-L-3-16-4-max-pool', ... % 196
    ... 'custom-2-L-3-16-8-max-pool', ... % 392
    ... 'custom-2-L-3-16-16-max-pool', ... % 784
    ...
    ... 'custom-2-L-3-64-1-max-pool', ... % 49
    ... 'custom-2-L-3-64-2-max-pool', ... % 98
    ... 'custom-2-L-3-64-4-max-pool', ... % 196
    ... 'custom-2-L-3-64-8-max-pool', ... % 392
    ... 'custom-2-L-3-64-16-max-pool', ... % 784
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... % ANYTHING-3072
    ... 'pca-project-into-1', ...
    ... 'pca-project-into-2', ...
    ... 'pca-project-into-4', ...
    ... 'pca-project-into-8', ...
    ... 'pca-project-into-16', ...
    ... 'pca-project-into-32', ...
    ... 'pca-project-into-64', ...
    ... 'pca-project-into-128', ...
    ... 'pca-project-into-256', ...
    ... 'pca-project-into-512', ...
    ... 'pca-project-into-1024', ...
    ... 'pca-project-into-2048', ...
    ... 'pca-project-into-3072', ...
    ... ... 'pca-project-into-4096', ...
    ...
    ... 'densely-project-indep-row-into-1-ensemble-1', ...
    ... 'densely-project-indep-row-into-2-ensemble-1', ...
    ... 'densely-project-indep-row-into-4-ensemble-1', ...
    ... 'densely-project-indep-row-into-8-ensemble-1', ...
    ... 'densely-project-indep-row-into-16-ensemble-1', ...
    ... 'densely-project-indep-row-into-32-ensemble-1', ...
    ... 'densely-project-indep-row-into-64-ensemble-1', ...
    ... 'densely-project-indep-row-into-128-ensemble-1', ...
    ... 'densely-project-indep-row-into-256-ensemble-1', ...
    ... 'densely-project-indep-row-into-512-ensemble-1', ...
    ... 'densely-project-indep-row-into-1024-ensemble-1', ...
    ... 'densely-project-indep-row-into-2048-ensemble-1', ...
    ... 'densely-project-indep-row-into-3072-ensemble-1', ...
    ... 'densely-project-indep-row-into-4096-ensemble-1', ...
    ...
    ... 'densely-project-indep-row-into-1-ensemble-1-relu', ...
    ... 'densely-project-indep-row-into-2-ensemble-1-relu', ...
    ... 'densely-project-indep-row-into-4-ensemble-1-relu', ...
    ... 'densely-project-indep-row-into-8-ensemble-1-relu', ...
    ... 'densely-project-indep-row-into-16-ensemble-1-relu', ...
    ... 'densely-project-indep-row-into-32-ensemble-1-relu', ...
    ... 'densely-project-indep-row-into-64-ensemble-1-relu', ...
    ... 'densely-project-indep-row-into-128-ensemble-1-relu', ...
    ... 'densely-project-indep-row-into-256-ensemble-1-relu', ...
    ... 'densely-project-indep-row-into-512-ensemble-1-relu', ...
    ... 'densely-project-indep-row-into-1024-ensemble-1-relu', ...
    ... 'densely-project-indep-row-into-2048-ensemble-1-relu', ...
    ... 'densely-project-indep-row-into-3072-ensemble-1-relu', ...
    ... 'densely-project-indep-row-into-4096-ensemble-1-relu', ...
    ...
    ... 'densely-project-indep-row-into-4-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-8-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-16-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-32-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-64-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-128-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-256-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-512-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-1024-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-2048-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-4096-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-8192-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-12288-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-16384-ensemble-1-vector-max-pool', ...
    ...
    ... 'densely-project-indep-row-into-4-ensemble-1-vector-min-pool', ...
    ... 'densely-project-indep-row-into-8-ensemble-1-vector-min-pool', ...
    ... 'densely-project-indep-row-into-16-ensemble-1-vector-min-pool', ...
    ... 'densely-project-indep-row-into-32-ensemble-1-vector-min-pool', ...
    ... 'densely-project-indep-row-into-64-ensemble-1-vector-min-pool', ...
    ... 'densely-project-indep-row-into-128-ensemble-1-vector-min-pool', ...
    ... 'densely-project-indep-row-into-256-ensemble-1-vector-min-pool', ...
    ... 'densely-project-indep-row-into-512-ensemble-1-vector-min-pool', ...
    ... 'densely-project-indep-row-into-1024-ensemble-1-vector-min-pool', ...
    ... 'densely-project-indep-row-into-2048-ensemble-1-vector-min-pool', ...
    ... 'densely-project-indep-row-into-4096-ensemble-1-vector-min-pool', ...
    ... 'densely-project-indep-row-into-8192-ensemble-1-vector-min-pool', ...
    ... 'densely-project-indep-row-into-12288-ensemble-1-vector-min-pool', ...
    ... 'densely-project-indep-row-into-16384-ensemble-1-vector-min-pool', ...
    ...
    ... 'densely-project-indep-row-into-4-ensemble-1-vector-avg-pool', ...
    ... 'densely-project-indep-row-into-8-ensemble-1-vector-avg-pool', ...
    ... 'densely-project-indep-row-into-16-ensemble-1-vector-avg-pool', ...
    ... 'densely-project-indep-row-into-32-ensemble-1-vector-avg-pool', ...
    ... 'densely-project-indep-row-into-64-ensemble-1-vector-avg-pool', ...
    ... 'densely-project-indep-row-into-128-ensemble-1-vector-avg-pool', ...
    ... 'densely-project-indep-row-into-256-ensemble-1-vector-avg-pool', ...
    ... 'densely-project-indep-row-into-512-ensemble-1-vector-avg-pool', ...
    ... 'densely-project-indep-row-into-1024-ensemble-1-vector-avg-pool', ...
    ... 'densely-project-indep-row-into-2048-ensemble-1-vector-avg-pool', ...
    ... 'densely-project-indep-row-into-4096-ensemble-1-vector-avg-pool', ...
    ... 'densely-project-indep-row-into-8192-ensemble-1-vector-avg-pool', ...
    ... 'densely-project-indep-row-into-12288-ensemble-1-vector-avg-pool', ...
    ... 'densely-project-indep-row-into-16384-ensemble-1-vector-avg-pool', ...
    ...
    ... 'densely-project-indep-row-into-16-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-32-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-64-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-128-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-256-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-512-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-1024-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-2048-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-4096-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-8192-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-16384-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-32768-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-49152-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-65536-ensemble-1-vector-max-pool', ...
    ...
    ... 'densely-project-indep-row-into-25-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-50-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-100-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-200-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-400-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-800-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-1600-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-3200-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-6400-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-12800-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-25600-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-51200-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-102400-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-204800-ensemble-1-vector-max-pool', ...
    ...
    ...
    ...
    ...
    ... ... ... ... % ANYTHING-3072 (add pooling to every layer, EXCEPT LAST)
    ... ... ... ... 'custom-1-L-3-99-1-max-pool', ... % 1024
    ... ... ... ... 'custom-1-L-3-99-2-max-pool', ... % 2048
    ... ... ... ... 'custom-1-L-3-99-4-max-pool', ... % 4096
    ... ... ... ...
    ... ... ... ... 'custom-2-L-3-16-1-max-pool', ... % 256
    ... ... ... ... 'custom-2-L-3-16-2-max-pool', ... % 512
    ... ... ... ... 'custom-2-L-3-16-4-max-pool', ... % 1024
    ... ... ... ... 'custom-2-L-3-16-8-max-pool', ... % 2048
    ... ... ... ... 'custom-2-L-3-16-16-max-pool', ... % 4096
    ... ... ... ...
    ... ... ... ... 'custom-3-L-3-16-1-max-pool', ... % 64
    ... ... ... ... 'custom-3-L-3-16-2-max-pool', ... % 128
    ... ... ... ... 'custom-3-L-3-16-4-max-pool', ... % 256
    ... ... ... ... 'custom-3-L-3-16-8-max-pool', ... % 512
    ... ... ... ... 'custom-3-L-3-16-16-max-pool', ... % 1024
    ... ... ... ... 'custom-3-L-3-16-32-max-pool', ... % 2048
    ... ... ... ... 'custom-3-L-3-16-64-max-pool', ... % 4096
    ... ... ... ...
    ... ... ... ... 'custom-4-L-3-16-1-max-pool', ... % 16
    ... ... ... ... 'custom-4-L-3-16-2-max-pool', ... % 32
    ... ... ... ... 'custom-4-L-3-16-4-max-pool', ... % 64
    ... ... ... ... 'custom-4-L-3-16-8-max-pool', ... % 128
    ... ... ... ... 'custom-4-L-3-16-16-max-pool', ... % 256
    ... ... ... ... 'custom-4-L-3-16-32-max-pool', ... % 512
    ... ... ... ... 'custom-4-L-3-16-64-max-pool', ... % 1024
    ... ... ... ... 'custom-4-L-3-16-128-max-pool', ... % 2048
    ... ... ... ... 'custom-4-L-3-16-256-max-pool', ... % 4096
    ... ... ... ...
    ... ... ... ... 'custom-5-L-3-16-1-max-pool', ... % 4
    ... ... ... ... 'custom-5-L-3-16-2-max-pool', ... % 8
    ... ... ... ... 'custom-5-L-3-16-4-max-pool', ... % 16
    ... ... ... ... 'custom-5-L-3-16-8-max-pool', ... % 32
    ... ... ... ... 'custom-5-L-3-16-16-max-pool', ... % 64
    ... ... ... ... 'custom-5-L-3-16-32-max-pool', ... % 128
    ... ... ... ... 'custom-5-L-3-16-64-max-pool', ... % 256
    ... ... ... ... 'custom-5-L-3-16-128-max-pool', ... % 512
    ... ... ... ... 'custom-5-L-3-16-256-max-pool', ... % 1024
    ... ... ... ... 'custom-5-L-3-16-512-max-pool', ... % 2048
    ... ... ... ... 'custom-5-L-3-16-1024-max-pool', ... % 4096
    ...
    ...
    ...
    ... % ANYTHING-3072 (add pooling to every layer)
    'custom-1-L-3-99-1-max-pool', ... % 256
    'custom-1-L-3-99-2-max-pool', ... % 512
    'custom-1-L-3-99-4-max-pool', ... % 1024
    ... 'custom-1-L-3-99-8-max-pool', ... % 2048
    ... 'custom-1-L-3-99-16-max-pool', ... % 4096
    ...
    ...
    ...
    ...
    ...
    ...
    'custom-2-L-3-16-1-max-pool', ... % 64
    'custom-2-L-3-16-2-max-pool', ... % 128
    'custom-2-L-3-16-4-max-pool', ... % 256
    'custom-2-L-3-16-8-max-pool', ... % 512
    'custom-2-L-3-16-16-max-pool', ... % 1024
    ... 'custom-2-L-3-16-32-max-pool', ... % 2048
    ... 'custom-2-L-3-16-64-max-pool', ... % 4096
    ...
    'custom-2-L-3-64-1-max-pool', ... % 64
    'custom-2-L-3-64-2-max-pool', ... % 128
    'custom-2-L-3-64-4-max-pool', ... % 256
    'custom-2-L-3-64-8-max-pool', ... % 512
    'custom-2-L-3-64-16-max-pool', ... % 1024
    ... 'custom-2-L-3-64-32-max-pool', ... % 2048
    ... 'custom-2-L-3-64-64-max-pool', ... % 4096
    ...
    ...
    ...
    ...
    ...
    ...
    ... 'custom-3-L-3-16-1-max-pool', ... % 16
    ... 'custom-3-L-3-16-2-max-pool', ... % 32
    ... 'custom-3-L-3-16-4-max-pool', ... % 64
    ... 'custom-3-L-3-16-8-max-pool', ... % 128
    ... 'custom-3-L-3-16-16-max-pool', ... % 256
    ... 'custom-3-L-3-16-32-max-pool', ... % 512
    ... 'custom-3-L-3-16-64-max-pool', ... % 1024
    ... 'custom-3-L-3-16-128-max-pool', ... % 2048
    ... 'custom-3-L-3-16-256-max-pool', ... % 4096
    ...
    ... 'custom-3-L-3-64-1-max-pool', ... % 16
    ... 'custom-3-L-3-64-2-max-pool', ... % 32
    ... 'custom-3-L-3-64-4-max-pool', ... % 64
    ... 'custom-3-L-3-64-8-max-pool', ... % 128
    ... 'custom-3-L-3-64-16-max-pool', ... % 256
    ... 'custom-3-L-3-64-32-max-pool', ... % 512
    ... 'custom-3-L-3-64-64-max-pool', ... % 1024
    ... 'custom-3-L-3-64-128-max-pool', ... % 2048
    ... 'custom-3-L-3-64-256-max-pool', ... % 4096
    ...
    ... 'custom-3-L-3-256-1-max-pool', ... % 16
    ... 'custom-3-L-3-256-2-max-pool', ... % 32
    ... 'custom-3-L-3-256-4-max-pool', ... % 64
    ... 'custom-3-L-3-256-8-max-pool', ... % 128
    ... 'custom-3-L-3-256-16-max-pool', ... % 256
    ... 'custom-3-L-3-256-32-max-pool', ... % 512
    ... 'custom-3-L-3-256-64-max-pool', ... % 1024
    ... 'custom-3-L-3-256-128-max-pool', ... % 2048
    ... 'custom-3-L-3-256-256-max-pool', ... % 4096
    ...
    ...
    ...
    ...
    ...
    ...
    ... 'custom-4-L-3-16-1-max-pool', ... % 4
    ... 'custom-4-L-3-16-2-max-pool', ... % 8
    ... 'custom-4-L-3-16-4-max-pool', ... % 16
    ... 'custom-4-L-3-16-8-max-pool', ... % 32
    ... 'custom-4-L-3-16-16-max-pool', ... % 64
    ... 'custom-4-L-3-16-32-max-pool', ... % 128
    ... 'custom-4-L-3-16-64-max-pool', ... % 256
    ... 'custom-4-L-3-16-128-max-pool', ... % 512
    ... 'custom-4-L-3-16-256-max-pool', ... % 1024
    ... 'custom-4-L-3-16-512-max-pool', ... % 2048
    ... 'custom-4-L-3-16-1024-max-pool', ... % 4096
    ...
    ... 'custom-4-L-3-64-1-max-pool', ... % 4
    ... 'custom-4-L-3-64-2-max-pool', ... % 8
    ... 'custom-4-L-3-64-4-max-pool', ... % 16
    ... 'custom-4-L-3-64-8-max-pool', ... % 32
    ... 'custom-4-L-3-64-16-max-pool', ... % 64
    ... 'custom-4-L-3-64-32-max-pool', ... % 128
    ... 'custom-4-L-3-64-64-max-pool', ... % 256
    ... 'custom-4-L-3-64-128-max-pool', ... % 512
    ... 'custom-4-L-3-64-256-max-pool', ... % 1024
    ... 'custom-4-L-3-64-512-max-pool', ... % 2048
    ... 'custom-4-L-3-64-1024-max-pool', ... % 4096
    ...
    ... 'custom-4-L-3-256-1-max-pool', ... % 4
    ... 'custom-4-L-3-256-2-max-pool', ... % 8
    ... 'custom-4-L-3-256-4-max-pool', ... % 16
    ... 'custom-4-L-3-256-8-max-pool', ... % 32
    ... 'custom-4-L-3-256-16-max-pool', ... % 64
    ... 'custom-4-L-3-256-32-max-pool', ... % 128
    ... 'custom-4-L-3-256-64-max-pool', ... % 256
    ... 'custom-4-L-3-256-128-max-pool', ... % 512
    ... 'custom-4-L-3-256-256-max-pool', ... % 1024
    ... 'custom-4-L-3-256-512-max-pool', ... % 2048
    ... 'custom-4-L-3-256-1024-max-pool', ... % 4096
    ...
    ... 'custom-4-L-3-1024-1-max-pool', ... % 4
    ... 'custom-4-L-3-1024-2-max-pool', ... % 8
    ... 'custom-4-L-3-1024-4-max-pool', ... % 16
    ... 'custom-4-L-3-1024-8-max-pool', ... % 32
    ... 'custom-4-L-3-1024-16-max-pool', ... % 64
    ... 'custom-4-L-3-1024-32-max-pool', ... % 128
    ... 'custom-4-L-3-1024-64-max-pool', ... % 256
    ... 'custom-4-L-3-1024-128-max-pool', ... % 512
    ... 'custom-4-L-3-1024-256-max-pool', ... % 1024
    ... 'custom-4-L-3-1024-512-max-pool', ... % 2048
    ... 'custom-4-L-3-1024-1024-max-pool', ... % 4096
    ...
    ...
    ...
    ...
    ...
    ...
    ... 'custom-5-L-3-16-1-max-pool', ... % 1
    ... 'custom-5-L-3-16-2-max-pool', ... % 2
    ... 'custom-5-L-3-16-4-max-pool', ... % 4
    ... 'custom-5-L-3-16-8-max-pool', ... % 8
    ... 'custom-5-L-3-16-16-max-pool', ... % 16
    ... 'custom-5-L-3-16-32-max-pool', ... % 32
    ... 'custom-5-L-3-16-64-max-pool', ... % 64
    ... 'custom-5-L-3-16-128-max-pool', ... % 128
    ... 'custom-5-L-3-16-256-max-pool', ... % 256
    ... 'custom-5-L-3-16-512-max-pool', ... % 512
    ... 'custom-5-L-3-16-1024-max-pool', ... % 1024
    ... 'custom-5-L-3-16-2048-max-pool', ... % 2048
    ... 'custom-5-L-3-16-4096-max-pool', ... % 4096
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ...
    ... % ANYTHING-5000+
    ... 'pca-project-into-1', ...
    ... 'pca-project-into-2', ...
    ... 'pca-project-into-4', ...
    ... 'pca-project-into-8', ...
    ... 'pca-project-into-16', ...
    ... 'pca-project-into-32', ...
    ... 'pca-project-into-64', ...
    ... 'pca-project-into-128', ...
    ... 'pca-project-into-256', ...
    ... 'pca-project-into-512', ...
    ... 'pca-project-into-1024', ...
    ... 'pca-project-into-2048', ...
    ... 'pca-project-into-4096', ...
    ... 'pca-project-into-5000', ...
    ...
    ... 'densely-project-indep-row-into-1-ensemble-1', ...
    ... 'densely-project-indep-row-into-2-ensemble-1', ...
    ... 'densely-project-indep-row-into-4-ensemble-1', ...
    ... 'densely-project-indep-row-into-8-ensemble-1', ...
    ... 'densely-project-indep-row-into-16-ensemble-1', ...
    ... 'densely-project-indep-row-into-32-ensemble-1', ...
    ... 'densely-project-indep-row-into-64-ensemble-1', ...
    ... 'densely-project-indep-row-into-128-ensemble-1', ...
    ... 'densely-project-indep-row-into-256-ensemble-1', ...
    ... 'densely-project-indep-row-into-512-ensemble-1', ...
    ... 'densely-project-indep-row-into-1024-ensemble-1', ...
    ... 'densely-project-indep-row-into-2048-ensemble-1', ...
    ... 'densely-project-indep-row-into-4096-ensemble-1', ...
    ... 'densely-project-indep-row-into-5000-ensemble-1', ...
    ...
    ... 'densely-project-indep-row-into-4-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-8-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-16-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-32-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-64-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-128-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-256-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-512-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-1024-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-2048-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-4096-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-8192-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-16384-ensemble-1-vector-max-pool', ...
    ... 'densely-project-indep-row-into-20000-ensemble-1-vector-max-pool', ...
  };




















