%-------------------------------------------------------------------------
function constructProstateImdbs()
  % TODO: this can be extended to support both v2 and v3, with different fold counts....
%-------------------------------------------------------------------------
  opts.dataset = 'prostate-v2-20-patients';
  opts.dataDir = '/Users/a6karimi/dev/data/source/prostate/v2 - 20 patients';
  opts.leave_out_type = 'special';
  opts.train_balance = false;
  opts.train_augment_healthy = 'none';
  opts.train_augment_cancer = 'none';
  opts.test_balance = false;
  opts.test_augment_healthy = 'none';
  opts.test_augment_cancer = 'none';
  opts.contrast_normalization = true;

  %% -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  opts.leaveOutIndices = [ 6    13    15     8];
  imdb = constructProstateImdb(opts);
  saveImdb(imdb, opts.dataset);


  %% -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  opts.leaveOutIndices = [ 4     1     2    20];
  imdb = constructProstateImdb(opts);
  saveImdb(imdb, opts.dataset);


  %% -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  opts.leaveOutIndices = [19    12     7     3];
  imdb = constructProstateImdb(opts);
  saveImdb(imdb, opts.dataset);


  %% -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  opts.leaveOutIndices = [18    16     5     9];
  imdb = constructProstateImdb(opts);
  saveImdb(imdb, opts.dataset);


  %% -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  opts.leaveOutIndices = [10    11    17    14];
  imdb = constructProstateImdb(opts);
  saveImdb(imdb, opts.dataset);

%-------------------------------------------------------------------------
function saveImdb(imdb, dataset)
%-------------------------------------------------------------------------
  positive_class_number = 2;
  negative_class_number = 1;

  fh_imdb_utils = imdbTwoClassUtils;
  save_file_name_prefix = sprintf( ...
    'saved-two-class-%s-pos%d-neg%d', ...
    dataset, ...
    positive_class_number, ...
    negative_class_number);

  [ ...
    data, ...
    data_train, ...
    data_train_positive, ...
    data_train_negative, ...
    data_train_indices, ...
    data_train_positive_indices, ...
    data_train_negative_indices, ...
    data_train_count, ...
    data_train_positive_count, ...
    data_train_negative_count, ...
    labels_train, ...
    data_test, ...
    data_test_positive, ...
    data_test_negative, ...
    data_test_indices, ...
    data_test_positive_indices, ...
    data_test_negative_indices, ...
    data_test_count, ...
    data_test_positive_count, ...
    data_test_negative_count, ...
    labels_test, ...
  ] = fh_imdb_utils.getImdbInfo(imdb, true);
  printConsoleOutputSeparator();
  save(...
    sprintf( ...
      '%s-unbalaned-train-%d-%d.mat', ...
      save_file_name_prefix, ...
      data_train_positive_count, ...
      data_train_negative_count), ...
    'imdb');
